### ISSUE TITLE
Clone Link in Doku nur mit Account nutzbar

### ISSUE THREAD

**Issue by schoeppler** [klein0r/fhem-style-haus-automatisierung#1]
Hey,

der clone link geht nur mit einem git account (git clone git@github.com:klein0r/fhem-style-haus-automatisierung.git hausautomatisierung-com), vielleicht wollen auch "normale" User das Repo clonen können :-)

also einfach: 
`git clone https://github.com/klein0r/fhem-style-haus-automatisierung.git hausautomatisierung-com`

Nur ne Anmerkung ;-)

Gruß
Christian

**Comment by klein0r** [comment]
Haben mir wirklich einige User berichtet 😢  Wenn man schon so lange mit git arbeitet, fällt einem gar nicht ein dass manche Menschen keinen GitHub-Account haben 😃 

Ist auf jeden Fall schon länger im Blogpost und jetzt auch in der Readme hier angepasst!

Danke für den Hinweis
