### ISSUE TITLE
Nach Update Version 2.8 und 2.10 in der Anzeige Teil 2

### ISSUE THREAD

**Issue by marios774** [klein0r/fhem-style-haus-automatisierung#100]
Die Probleme mit dem Theme enden leider nicht...

Nach dem erfolgreichen löschen des WEB Attributs JAVA bekomme ich folgende Fehlermeldung auch nach löschen des Caches..

Theme-SA aktiviert für vollen Funktionsumfang  attr....
Außerdem ist die Eingabezeile aktuell max. 1 Zeichen breit.

**Comment by klein0r** [comment]
update all, shutdown restart (Version 2.11), Browser-Cache leeren, Reload, läuft

Die JavaScript Meldung ist in den neuen Versionen gar nicht mehr enthalten, daher musst Du eine alte JS-Datei haben.
