### ISSUE TITLE
Zigbee Übersicht wird nicht dargestellt

### ISSUE THREAD

**Issue by flummy1978** [klein0r/fhem-style-haus-automatisierung#101]
Hallöchen,

beim Einrichten meiner Zigbee Devices ist mir ein Fehler aufgefallen, der die Darstellung der Zigbee2MQTT Devices übersichtlich darstellt. Leider funktionert das im Hausautomatisierungs Style (fast) gar nicht :(  Im Screenshot sieht man beide Styles. Im roten Rahmen des HA Styles sind die Objekte dargestellt, aber wirklich in miniminimini Darstellung.
Vielleicht hast Du da ja eine schöne Idee wie man das kurzfristig ändern kann :) 

Wenn Du da noch mehr Infos (Quellcodes oder was auch immer) brauchst, nur zu, ich lass Dir alles zukommen, was Du brauchst) 

Viele Grüße
Andreas

![screen1](https://user-images.githubusercontent.com/49339206/57982360-bd12c700-7a44-11e9-93f4-a9eef67c10b4.jpg)
![screen2](https://user-images.githubusercontent.com/49339206/57982361-bd12c700-7a44-11e9-87df-9f9729c68ed8.jpg)

**Comment by Ulli2k** [comment]
Ich hab das selbe Problem! 
Mit der 2.10er version ging es...

**Comment by klein0r** [comment]
Wie komme ich denn überhaupt an die Map? Geht das nur mit MQTT2? Oder auch mit einem externen Broker?

**Comment by aHVzY2g** [comment]
Ich habe den selben fehler, @klein0r es geht auch mit MQTT2 wenn du das an dein Brocker bindest, falls du das meinst "define myBrocker MQTT2_CLIENT <host>:<port>"
