### ISSUE TITLE
Fehlerhafte Darstellung von CalendarEventsAsHtml()

### ISSUE THREAD

**Issue by binford6000** [klein0r/fhem-style-haus-automatisierung#102]
Hallo,
CalendarEventsAsHtml() erzeugt html Code in der Form:
```
07.06.19	72h	Kinder
21.06.19	72h	Kinder
05.07.19	72h	Kinder
22.07.19	19d	Kinder
```
Die Ausgabe ist allerdings anders:

![calendar](https://user-images.githubusercontent.com/29679540/59031263-781fca80-8863-11e9-8d1f-d4d2beda7157.PNG)

Ist es möglich das zu entzerren?
VG Sebastian

**Comment by klein0r** [comment]
Wird in 2.12 gefixt sein, danke für den Hinweis!
