### ISSUE TITLE
Fehlerhafte Darstellung bei Verwendung attr "columns" in FHEMWEB

### ISSUE THREAD

**Issue by binford6000** [klein0r/fhem-style-haus-automatisierung#103]
Hallo,
wenn ich das Attribut columns in einem FHEMWEB device konfiguriere werden die Spalten nicht auf der gleichen Höhe dargestellt (Siehe Screenshot):

`attr WEB columns 90_System->91_Interfaces:Hardware|Software`

![columns](https://user-images.githubusercontent.com/29679540/59095144-0ce40000-8918-11e9-8450-52cc0a97bacb.PNG)

VG Sebastian

EDIT: Bei gleicher Anazhl an Geräten in den Spalten ist die Höhe auch identisch!

![columns1](https://user-images.githubusercontent.com/29679540/59095461-d8bd0f00-8918-11e9-94d6-33cce438eddc.PNG)

**Comment by klein0r** [comment]
Sollte nun passen (seit 2.12)
