### ISSUE TITLE
Display Plot Values

### ISSUE THREAD

**Issue by HFOdiver66** [klein0r/fhem-style-haus-automatisierung#106]
Hi Matthias,
tolle Arbeit, herzlichen Dank für Deine Bemühungen -> hat mir, als FHEM-Anfänger, beim Einstieg sehr geholfen.

Bei der Auswertung der Plots ist der relevante Wert + Zeit nur schwer zu erkennen. Somit würde ich die Farbe (aktuell weiß) der Schrift gern auf eine dunkle Schrift ändern. #16 konnte das Problem nicht lösen.   

 
![myPLOT](https://user-images.githubusercontent.com/50677188/62413122-61e87d80-b60c-11e9-8ed4-e69eb875c7d7.JPG)

Nochmals Dank & weiter so,
Sven

**Comment by aHVzY2g** [comment]
Wenn folgendes zum css hinzugefügt wird funktoniert es

`#svgmarker {
    color: gray;
}`

**Comment by HFOdiver66** [comment]
Moin Marlon,

klasse, vielen Dank.

Nur leider gehen die Einstellungen nach einem „update all“ verloren.

 

VG

Sven 

 

Von: Marlon Spangenberg [mailto:notifications@github.com] 
Gesendet: Donnerstag, 26. Dezember 2019 23:30
An: klein0r/fhem-style-haus-automatisierung
Cc: HFOdiver66; Author
Betreff: Re: [klein0r/fhem-style-haus-automatisierung] Display Plot Values (#106)

 

Wenn folgendes zum css hinzugefügt wird funktoniert es

#svgmarker { color: gray; }

**Comment by aHVzY2g** [comment]
Ich bin grade dabei mich in dieses scss einzuarbeiten und werde dann eine pull request machen
