### ISSUE TITLE
Darstellungsfehler untergeordneter Räume

### ISSUE THREAD

**Issue by matsahm** [klein0r/fhem-style-haus-automatisierung#107]
Die Pfeile zum Aufklappen der untergeordneten Räume werden nicht schön dargestellt. Ich vermute mal, dass es kaum einer nutzt und es deswegen bisher nicht berücksichtigt wurde. Meine CSS-Kenntnisse reichen leider nicht aus, dies zu korrigieren. Kann hier jmd. helfen?
![Bildschirmfoto 2019-08-05 um 23 33 16](https://user-images.githubusercontent.com/25862848/62496548-83e32b00-b7d9-11e9-93bf-6282ca8b00da.png)

**Comment by klein0r** [comment]
Du nutzt Version 1.2 - diese wird seit Jahren nicht mehr unterstüzt. In Version 2 ist das Design an der Stelle korrekt. Also den alten Skin deinstallieren und diesen nach der Anleitung nutzen:

https://github.com/klein0r/fhem-style-haus-automatisierung/tree/version-2
