### ISSUE TITLE
Update schlägt immer fehl

### ISSUE THREAD

**Issue by matsahm** [klein0r/fhem-style-haus-automatisierung#109]
Ich erhalte immer ein Fehler beim Versuch das Template zu aktualisieren.

Befehl:
`update all ha_theme`

Fehlermeldung:
open ./www/hausautomatisierung-com/images/haus_automatisierung.png failed: Permission denied, trying to restore the previous version and aborting the update

**Comment by klein0r** [comment]
Kann es sein, dass Du das Bild selbst ausgetauscht hast? Schau mal nach den Dateirechten
