### ISSUE TITLE
SVG Chart Bezeichnung nicht lesbar

### ISSUE THREAD

**Issue by Groepi** [klein0r/fhem-style-haus-automatisierung#11]
Hallo Matthias,

Die SVGs sind in der V2.2 immer noch unlogisch. Warum machst Du die Schriftart nicht in Orange wieder die anderen Devices?

Das die Fläche Rot ist und die Line dann blau macht auch keinen Sinn.

Grüße Gröpi

![bildschirmfoto 2017-08-18 um 06 26 32](https://user-images.githubusercontent.com/18686150/29444385-80992b78-83df-11e7-8e17-628d104ac584.png)

**Comment by SmartSpiegel** [comment]
Bei mir überlagert sich leider auch alles. Die Graphen sind kaum zu lesen. Durch Version 2.2 kann ich aber nun die Farben selbst bestimmen, was vorher nicht möglich war. 
Ein Update zur besseren Lesbarkeit der Graphen würde ich mir sehr wünschen :)

**Comment by XXL-Wing** [comment]
Vor allem wenn man die Graphen in Gruppen hat, deren Linien abwechselnd weiss und hellgrau hinterlegt sind sind die Graphen nicht lesbar :-(

**Comment by Trrw** [comment]
Hat sich bereits etwas geändert :)?

**Comment by klein0r** [comment]
Das Problem ist, dass es mehrere Möglichkeiten gibt:

- Plot einfach so, durchsichtig
- Plot in Gruppe (auf Grau)
- Plot in Gruppe (auf Hellgrau)

Orange finde ich nicht so schön. Da ich Plots selber nicht in Gruppen packe, sieht es bei mir eigentlich immer ganz gut aus. Gruppen mit Plots bekommen scheinbar auch die Klasse "no-background". Diese habe ich angepasst.

Ich mache das hier erstmal zu. Vorschläge zu Version 2.5 (kommt bald) bitte in einem neuen Issue.
