### ISSUE TITLE
how to deinstall?

### ISSUE THREAD

**Issue by e-t-h** [klein0r/fhem-style-haus-automatisierung#111]
Wie kann man sich von diesem style wieder trennen? 
Die Diagrammfarben sind z.B. überhaupt nicht zu unterscheiden, sicher ästhetisch ansprechend, aber ein hellbraun von einem dunkelbraun zu unterscheiden ist nicht so einfach. 

Danke für einen Tip.

**Comment by klein0r** [comment]
Einfach unter Styles einen anderen auswählen. Ansonsten alle Dateien löschen, welcher in dieser Datei aufgeführt sind: https://github.com/klein0r/fhem-style-haus-automatisierung/blob/version-2/controls_ha_theme.txt
