### ISSUE TITLE
Floorplan Menü Fehler

### ISSUE THREAD

**Issue by stonemuc** [klein0r/fhem-style-haus-automatisierung#112]
Hallo,

mir ist aufgefallen, dass sich seit einem der letzten Updates ein Fehler beim Floorplan eingeschlichen hat. Das Menü war dort immer links am Bildschirmrand, so wie bei FHEM üblich. Nun ist es im Floorplan plötzlich rechts und somit passen die angeordneten Objekte nicht mehr zum Hintergrundbild, da dieses ja nun weiter links liegt.

Bitte fixen...

**Comment by klein0r** [comment]
Das Menu habe ich mit Absicht verschoben. Dadurch stimmen leider die Positionen nicht mehr und müssen einmal neu angepasst werden.
