### ISSUE TITLE
Fehlerhafte Darstellung in Firefox: weblink cmdList

### ISSUE THREAD

**Issue by s1738berger** [klein0r/fhem-style-haus-automatisierung#114]
Bei einem weblink, cmdList wird ein oranger 2px Border auf der nächsten Zeile angezeigt in Firefox und Safari (linkes Bild). Chrome zeigt nichts an (rechts).
Es scheint die Abtrennung bei 25% zu sein, die hier irgendwie keinen Sinn macht.

![cmdList-firefox-chrome](https://user-images.githubusercontent.com/368973/66359522-c3fc9080-e977-11e9-8c2d-fa40547bf54b.jpg)

**Comment by klein0r** [comment]
Hast Du mal ein define dafür?

**Comment by mackshot** [comment]
Ich konnte es mit diesem define
`define systemCommands weblink cmdList pair:Pair:set+cul2+hmPairForSec+60 restart:Restart:shutdown+restart `
nicht nachvollziehen

**Comment by mackshot** [comment]
@s1738berger besteht das Problem im neuesten Firefox noch?

**Comment by s1738berger** [comment]
Ja, das Problem besteht auch mit Firefox 71. Habe gerade bemerkt dass es nur auftritt wenn es einer Gruppe zugeordnet wird. Auch mit dem define von mackshot.

**Comment by mackshot** [comment]
@s1738berger Pull-Request mit Fix dafür liegt vor :)

**Comment by s1738berger** [comment]
hab die Änderungen manuell in meine CSS-Datei übernommen, funktioniert prima. Kommt hoffentlich bald im regulären Update. Und wieder ist die Welt ein kleines bisschen besser geworden :-)
Vielen Dank

**Comment by mackshot** [comment]
Danke :) @klein0r Now it is your turn ;)

**Comment by klein0r** [comment]
@mackshot Mutige Änderung. Testest Du die immer durch das ganze System?

**Comment by mackshot** [comment]
@klein0r Eine noch mutigere Änderung ist in einem anderen PR ;)
Also ich klicke mich durch mein System durch und schaue ob ich irgendwelche Probleme finde, aber das ist natürlich nur eine Stichprobe und da ich etwa das Attribut "group" kaum verwende, sicher keine Garantie dafür, dass ich nichts zerstört habe. Vielleicht sollten ich mir (oder wir uns?) mal ein Testsystem mit den meisten Konstellationen aufsetzen in dem man das testen kann...

**Comment by klein0r** [comment]
Ja, ich habe so ein System laufen. Allerdings zeigt die Vergangenheit, dass man mit Änderungen sehr vorsichtig sein muss. Irgendwo fällt einem das sonst wieder auf die Füße. Sei es in der commandref, dem Monitor oder sonstwo.

Das liegt natürlich daran, dass man kaum Klassen hat um die Änderungen besser eingrenzen zu können...

**Comment by mackshot** [comment]
@klein0r Kannst Du das System irgendwie sharen für mich zu testen, oder soll ich mir hier noch selber etwas aufsetzen?

**Comment by s1738berger** [comment]
Mit dieser Änderung habe ich bis jetzt noch keine Kollateralschäden feststellen können - aber eben nur auf meinem System.

Noch ein paar Gedanken zum Thema Testen.
Aus Erfahrung mit anderen Systrmen denke ich dass es em effizientesten ist, wenn man mit möglichst vielen Systemen, die von unterschiedlichen Personen betreut werden, testen kann. Damit deckt man am besten die vielen Möglichkeiten ab, die bei solch komplexen Gebilden auftreten können. Ein Testaufbau, so umfanreich err auch sein mag, deckt immer niur einen Teil ab.
Ich stelle maine Installation gerne für solche Tests zur Verfügung und teste Änderungen auch gerne selber durch. Aber eben, auch in meinem System kommen lange nicht alle Möglichkeiten vor. Deshalb ist auch das immer nur eine Teilansicht.

Ich betreibe FHEM auf einem RaspberryPi3 der über eine FritzBox mit Portforwarding mit der Welt verbunden ist. Neben einigen Homematic Geräten(Licht, Heizung, Fenster, Türen), sind etwas MQTT (Sonoff) und ZigBee (RapsBee von dresden-elekrtonik auf anderem RapsberryPI) im Einsatz. Plots werden mit Grafana erzeugt und mittels IFRAME angezeigt. FHEM ist mit fhem-style-haus-automatisierung ansehlich gemacht.
Gibt es eine Möglichkleit FHEM einem User nur für lesenden Zugriff anzubieten?
So, genug für heute. Gruss and Tester und Programmierer
Stefan

**Comment by mackshot** [comment]
Hallo Stefan,
vielen Dank für Dein Feedback. Habe auch keine Probleme festgestellt.

Ich hatte mal überlegt ein System (für einen ausgewählten Personenkreis zugänglich) mit allen denkbaren Konstellationen aufzusetzen, aber stimme Dir zu, dass es schwer ist hier alles abzudecken.
Von daher finde ich Deinen Ansatz, hier einen Testerkreis zu haben der soetwas testen auch nett.

@klein0r : Wie wäre es denn, wenn Du einen dedizierten Branch (pre-release oder beta) anlegst in dem alle PR zunächst überführt werden. Dort testen dann alle die wollen und nach einer bestimmten Zeit wird der Pre-release / die Beta dann in den Master gemergt?
Wenn Du hier Unterstützung brauchst beim Build etc, könnte ich mir vorstellen, dass @s1738berger und ich hier bereitstehen.
Alternativ kann ich anbieten, dass ich solche Pre-Releases in meinem Fork abbilde - wäre für mich aber eher zweite Wahl.

Liebe Grüße
Markus

**Comment by mackshot** [comment]
@klein0r, kann das hier nicht auch geschlossen werden?

**Comment by s1738berger** [comment]
Ja, das ist erledigt.
Danke und Gruss, Stefan
