### ISSUE TITLE
devStateIcon kein Editor

### ISSUE THREAD

**Issue by evolvo187** [klein0r/fhem-style-haus-automatisierung#115]
beim attr .... devStateIcon öffnet sich der DEF-Editor bzw. Code-Editor nicht

**Comment by mackshot** [comment]
Kann den Fehler nicht nachvollziehen. Kannst Du mal den Browser-Cache leeren und dann nochmal testen?

**Comment by klein0r** [comment]
Hat er sich dort jemals geöffnet?! Ist mir gar nicht bekannt.
