### ISSUE TITLE
Time Tics im Plot fehlen

### ISSUE THREAD

**Issue by uidgh1153** [klein0r/fhem-style-haus-automatisierung#116]
Hallo,
auch ich möchte mich erstmal für den tollen Job bedanken, den Du im Rahmen der FHEM Tutorials machst bzw. gemacht hast.
Dein Skin/Style gefällt mir gut, weswegen ich ihn mir auch auf meine FHEM Installation gezogen habe.
Zwei Punkte sind m.E. aber nicht so gut gelungen:
1. Bei der Zeitachsen-Darstellung in den Plots sind die Stunden-Tics verschwunden. Die Standard-Aufteilung im 4-Stunden-Abstand ist etwas grob. Bei den anderen Styles (z.B. ios7) sind die Tics zu sehen. Wo muss man dran drehen ? (Bin kein CSS-Experte)
2. Habe die Fahrplan-Auakunft (98_DBPlan.pm) genutzt. Wenn Zusatz-Informationen geliefert werden, wird kein Zeilen-Umbruch in der entsprechenden Tabelle gemacht, sondern die Tabelle über den Bildschirmrand erweitert. Um alles sehen zu können, muss man scrollen:
![image](https://user-images.githubusercontent.com/32861040/70375517-e6bb0f00-18fe-11ea-9327-e86e301dbcce.png)
Auch dies ist im Style ios7 m.E. besser gelöst. Gibt es hierfür auch irgendwo eine Stellschraube in den css-Dateien?

**Comment by mackshot** [comment]
Problem 1 mit Pull Request #124 adressiert.

**Comment by mackshot** [comment]
Problem 2 auch gelöst, allerdings bin ich nicht sicher was die Changes im PR möglicherweise zerstören. @klein0r bitte SEHR kritisch prüfen und auch testen in Deiner FHEM-Instanz!
