### ISSUE TITLE
Verhalten bei der Speicherung innherhalb des neuen Styles

### ISSUE THREAD

**Issue by AchimL** [klein0r/fhem-style-haus-automatisierung#117]
Bei der Speicherung von Änderungen kommt folgende Fehlermeldung:
**Last unsaved structural changes:
  attr WEB stylesheetPrefix hausautomatisierung...**
Eine Speicherung ist NICHT möglich
Nach dem Wechsel auf den Original-Style funktioniert wieder alles
![Screenshot](https://user-images.githubusercontent.com/59150188/71328110-d2d3f780-2511-11ea-9720-d796c000bc64.jpg)

**Comment by klein0r** [comment]
Das passiert wenn Du auf das Ausrufezeichen klickst, statt auf Save config. So ist der FHEM-Standard. Bei mir klappt es mit allen Browsern

**Comment by AchimL** [comment]
Hallo Matthias,
Danke für die Rückmeldung.
Ich habe Deinen Theme noch einmal neu installiert, jetzt bleiben die Icons beim Wechsel erhalten.

⁣
H.-J. Lütgering

Gesendet mit BlueMail ​
