### ISSUE TITLE
DefStateIcons gehen nach Style-Änderung verloren

### ISSUE THREAD

**Issue by AchimL** [klein0r/fhem-style-haus-automatisierung#118]
Ich hatte z. B. für meine Jalosuien die "Shutter"-Icons ausgewählt.
Nach dem wechsel des Design (z. B. auf FHEM-Standard) waren sie verschwunden und wurden durch Glühbirnen ersetzt.

Achim

**Comment by klein0r** [comment]
Hast Du einen Screenshot dazu? Welche Icons hattest Du denn gewählt?
