### ISSUE TITLE
kein Hintergrund in Graphen 

### ISSUE THREAD

**Issue by Shantos** [klein0r/fhem-style-haus-automatisierung#12]
Hi Matthias, seit 2.2 kein haben meine Graphen keinen Hintergrund mehr. Bei 2.1 war noch alles super :/

![fhem fehler](https://user-images.githubusercontent.com/16309542/29465656-563246f2-843a-11e7-96c4-26e6c0725497.JPG)

**Comment by SmartSpiegel** [comment]
Gleiche Problem bei mir :(

**Comment by Chris383838** [comment]
Bei mir das gleiche Problem.

**Comment by Volker0815** [comment]
Ich habe auch dasselbe Problem. Die SVGs einer Group zuordnen bringt auch nix, weil dann die Beschriftung weiss auf weissem Hintergrund nicht mehr lesbar ist.

**Comment by Shantos** [comment]
Hat wer das Problem mittlerweile in den Griff bekommen?

**Comment by Trrw** [comment]
Leider bei Version 2.4 immernoch genau das gleiche Problem...

**Comment by Trrw** [comment]
Gibt es einen Lösungsansatz woran es liegen kann? Kann man es bis dahin vllt selbst fixen bis der Fehler im offiziellen Update behoben wird? :)

**Comment by Volker0815** [comment]
Ich hab als Workaround die Linien in den Graphen dicker gemacht (Width = 2), damit man sie besser erkennen kann.

**Comment by klein0r** [comment]
Ich habe sehr viele Mails bekommen, dass durchsichtige Graphen nicht mehr gingen. Jetzt bekomme ich Beschwerden hier, dass man diese nicht mehr lesen kann :) Ist schon ziemlich schwer es allen Recht zu machen - bzw. unmöglich. Ich lasse es jetzt erstmal so wie es ist. Außer jemand macht einen super Pull-Request bei welchem alles schön aussieht 😄

**Comment by Trrw** [comment]
Okay schade! Könntest du mir sagen wie selber den Hintergrund auf ein Grau ändern kann?
Vielen Dank :)

**Comment by cyablo** [comment]
Das wäre eine nette Info. Kann nicht nachvollziehen warum man Graphen durchsichtig haben möchte, die sind so wirklich schlecht lesbar und es sieht auch "out of place" aus.

**Comment by Glenn-Dandy** [comment]
Ja fand es auch schlecht lesbar.
Aber so ein richtiges Problem ist es nicht. 

Wenn man den Hintergrund weiß mag was eigentlich bei dem Design echt gut aussieht.

Geht ihr in die "hausautomatisierung_comsvg_style.css"

Und fügt bei 
svg .border { stroke: #e56524; } ein fill: #ffffff ein

Also so 
svg .border { stroke: #e56524; fill: #ffffff}
Jetzt haben die graphen einen weißen hintergrund und sind gut ablesbar.

Nachteil: bei jeden update muss mans wieder einfügen. 
Ich geh deswegen sovor.  update check,  wenn ha-theme kein update hat dann nur update fhem. 

Update ha-theme ändert er eure weißen graphen wieder in durchsichtige.

**Comment by Trrw** [comment]
Super vielen Dank! Hat wunderbar funktioniert. Jetzt kann ich die Graphen wieder lesen :)

**Comment by klein0r** [comment]
Habe ich in 2.6 doch wieder auf weiß angepasst.
