### ISSUE TITLE
Linkfarbe bei motd

### ISSUE THREAD

**Issue by jpawlowski** [klein0r/fhem-style-haus-automatisierung#125]
In Version 2.15 werden die motd jetzt in einem orangenen Kasten dargestellt.
Links, die innerhalb des Textes sind, werden leider ebenfalls Orange dargestellt und sind somit nicht erkennbar.

**Comment by klein0r** [comment]
Grrr... hast Du nicht genug Trust in der FHEM-Community um mal ein paar vernünftige Klassen und von mir aus auch IDs einzuführen?!

**Comment by jpawlowski** [comment]
I wish!
Ich und trust? Werde wohl eher als Störenfried wahrgenommen und man ist sicher froh, wenn ich mal nen halbes Jahr was anderes zu tun habe ;-)

**Comment by klein0r** [comment]
Ach, du auch? 😢

**Comment by mackshot** [comment]
Ich glaube das Problem habe ich mit #123 bereits gefixt. Kannst Du mal testen, ob Du das bestätigen kannst @jpawlowski ? Danke

**Comment by jpawlowski** [comment]
@mackshot dieser Commit ist ja bereits Teil von Version 2.15. Ich habe den Zustand beschrieben, wie er bei dieser Version ist.

**Comment by mackshot** [comment]
@jpawlowski Danke für die Erläuterung und sorry für das Durcheinander. PR #129 sollte es fixen. Preview findest Du im PR
