### ISSUE TITLE
Default Branch festlegen

### ISSUE THREAD

**Issue by jpawlowski** [klein0r/fhem-style-haus-automatisierung#128]
Vielleicht kannst du gelegentlich mal den [Default Branch](https://help.github.com/en/github/administering-a-repository/setting-the-default-branch) auf `version-2` setzen, dann muss man das nicht immer manuell auswählen ;-)
Ggf. kannst du dann den `master` Branch auch löschen, die Historie bleibt ja trotzdem.

**Comment by klein0r** [comment]
Ja, wollte ich schonmal. Dann kommt als Warnung: "Changing your default branch can have unintended consequences that can affect new pull requests and clones."

Das konnte ich nicht einordnen wie tragisch das wohl wird und habe es gelassen 😄

**Comment by jpawlowski** [comment]
IMHO ist das ja genau der Effekt, den man dann auch haben will ;-)
Ich hab bei ganz vielen Repos den Branch umgestellt, alles ganz problemlos. `master` ist nur ein Name wie jeder andere auch, kann man theoretisch auch jederzeit wieder umändern.

**Comment by klein0r** [comment]
Ok, scheint alles geklappt zu haben :) Dachte ich verliere sonst irgendwelche Pull-Requests o.ä.
