### ISSUE TITLE
Hintergrundbild wandert mit

### ISSUE THREAD

**Issue by ckoop** [klein0r/fhem-style-haus-automatisierung#13]
Hallo Matthias,

das Hintergrundbild von dem Skin sollte fix sein und sich nicht vergrößern/mitwandern. 

Problem: 
Bei einer Auflösung von 1920:1080 wandert der "weiße" Hintergrund (Versionsnr.) nach rechts. Folge, die Kommandozeile ist dann beeinträchtigt durch die weiße Schrift. Und die Proportionen passen auch nicht mehr (siehe Anhang). Wenn ich das Browserfenster verkleinere, ist alles gut.

Browser: Chrome 
OS:  Ubuntu 16.04 LTS

![bildschirmfoto von 2017-08-19 20-44-00](https://user-images.githubusercontent.com/31166402/29489357-94f5a8da-851f-11e7-9603-4ec171b23eef.png)

**Comment by marios774** [comment]
Gleiches Problem auf dem MAC

Browser: Safari und Chrome
OS: macOS 10.12 / macOS 10.13

**Comment by TottiToad** [comment]
Ebenfalls das selbe Problem beim MAC

Ist es evtl. möglich ein Benutzerdefiniertes Hintergrundbild zu nutzen ?

Zur Zeit packe ich immer ein eigenes Hintergrundbild in FHEM um die Kommandozeile lesen zu können. Jedoch ist dies ja nach jedem update wieder weg.

Wäre schön wenn man das Problem beheben könnte.

**Comment by ckoop** [comment]
Mit dem Firefox scheint es das Problem nicht zu geben.

Firefox 56.0
OS: Ubuntu 16.04 LTS

**Comment by klein0r** [comment]
Wird in der nächsten Version (2.5) behoben sein :)
