### ISSUE TITLE
Es werden nicht alle Zeichen im erweiterten Editor angezeigt

### ISSUE THREAD

**Issue by DerDoubleD** [klein0r/fhem-style-haus-automatisierung#130]
Bei langen Zeilen wenden im erweiterten Editor die letzten 3 Zeichen abgeschnitten.
Brouser ist crome

Auf dem Screenshot siht man 890 nicht
![snip](https://user-images.githubusercontent.com/47006370/72387305-7dab9000-3723-11ea-8faa-8d5af88d888a.JPG)

**Comment by mackshot** [comment]
Ich bin jetzt zunächst einmal etwas verwirrt und würde gerne dies erstmal auflösen:

1. In der Installationsanleitung zum Skin steht man solle
`attr WEB codemirrorParam { "theme": "blackboard", "lineNumbers":true, "lineWrapping": true, "height": "auto", "autocomplete": true }`
setzen. Es wird also das Line Wrapping explizit angeschaltet. Im StyleSheet des Skins wird dann folgende Regel definiert: `#content pre.CodeMirror-line { white-space: pre; }`. Dadurch werden Zeilenumbrüche verhindert. Dadurch tritt dann wiederum auch das hier beschriebene Problem auf, Kann das bei mir lokal reproduzieren.

2. Soll der Skin überhaupt mit `"lineWrapping": false` funktionieren? Weil wenn ja, funktioniert dieser dann nicht mehr korrekt, wenn man die oben genannte Regel entfernt. Das müsste man sich dann nochmal genauer anrufen

@klein0r Wie ist denn hier Dein Wunsch alter Vater dieses Skins?
@DerDoubleD Gehe ich überhaupt recht in der Annahme, dass Du den Skin mit `"lineWrapping": false` benutzt, aber das LineWrapping gar nicht greift?

Würde mich freuen, wenn wir auf das Thema hier auch mal einen Deckel bekommen ;)

Edit: Nachtrag: Ich glaube wenn wir die bestehende Regel (s.o.) durch `#content pre.CodeMirror-line { padding-right: 0; }` ersetzen hätte wir das Ziel beide Fälle funktionsfähig zu machen schon erzielt. Habe ich aber noch nicht ausführlich getestet.

**Comment by klein0r** [comment]
@mackshot Ich bin schon fast daran verzweifelt, wie sich das CSS und die Container zusammen mit dem Editor verhalten. Ständig ist irgendwas breiter oder läuft über. Ich bin als Softwareentwickler ja nicht so fit in Fronend-Themen und CSS ist für mich eher Quälerei als Spaß 😄 Von daher nimm Dich der Sache gerne an.

**Comment by DerDoubleD** [comment]
@mackshot
Ja, genau.
Wäre cool, wenn du das fixen könntest...

Gruß
Daniel

Matthias Kleine <notifications@github.com> schrieb am Do., 7. Mai 2020,
17:25:

**Comment by mackshot** [comment]
@DerDoubleD Ich habe mal eine Beta gebaut, die das Problem fixen sollte. In meiner Test- und Produktivumgebung arbeitet der Thema jetzt wie gewünscht, egal ob ich lineWrapping an- oder ausschalte.
Kannst Du das mal Prüfen?

Dazu musst Du meinen Beta-Skin installieren, der parallel zu dem von klein0r läuft (sollte keine Konflikte geben). Anleitung und Infos findest Du [hier](https://github.com/mackshot/fhem-style-haus-automatisierung).

**Comment by DerDoubleD** [comment]
Die Installation schlägt fehl da es die angegebene Datei nicht gibt.
https://raw.githubusercontent.com/klein0r/fhem-style-haus-automatisierung/version-2/controls_ha_theme_mackshot.txt


Gruß
Daniel


Am Do., 14. Mai 2020 um 09:44 Uhr schrieb Matthias Kleine <
notifications@github.com>:

**Comment by mackshot** [comment]
@DerDoubleD Sorry, da war die Anleitung an einer Stelle noch fehlerhaft... `update add https://raw.githubusercontent.com/mackshot/fhem-style-haus-automatisierung/version-2/controls_ha_theme_mackshot.txt`

**Comment by DerDoubleD** [comment]
Hallo Markus,
danke für Deine mühe.
Leider wird auch mit dem neuen Link die Datei nicht gefunden.

Gruß
Daniel


Am Do., 14. Mai 2020 um 15:45 Uhr schrieb Markus Pullmann <
notifications@github.com>:

**Comment by DerDoubleD** [comment]
So funktioniert es
https://raw.githubusercontent.com/mackshot/fhem-style-haus-automatisierung/version-2beta/controls_ha_theme_mackshot.txt

Aber es kommt noch zu einem Fehler
2020.05.14 19:12:59 1 : Downloading
https://raw.githubusercontent.com/mackshot/fhem-style-haus-automatisierung/version-2beta/controls_ha_theme_mackshot.txt
2020.05.14 19:12:59 1 :
2020.05.14 19:12:59 1 : ha_theme_mackshot
2020.05.14 19:13:00 1 : nothing to do...
2020.05.14 19:13:00 1 : Downloading
2020.05.14 19:13:00 1 : Cannot parse , probably not a valid http control file



Gruß
Daniel Deml


Am Do., 14. Mai 2020 um 19:06 Uhr schrieb Daniel <Daniel.Deml@gmx.de>:

**Comment by mackshot** [comment]
Zunächst einmal ein dickes Sorry für das hin und her mit der URL. Du hast absolut recht, die richtige URL lautet:
https://raw.githubusercontent.com/mackshot/fhem-style-haus-automatisierung/version-2beta/controls_ha_theme_mackshot.txt

Eigentlich sollte diese URL aber dann auch funktionieren. Führe doch bitte mal ein `update list` aus und prüfe, ob Du hier noch alte falsche URLs findest. Wenn ja kannst du diese mit `update delete URL` entfernen.

Im Zweifel kannst Du auch mal ein `update force ha_theme_mackshot` ausführen. Ggf. vorher auch fhem einmal neustarten.

Bitte berichte mal ob es klappt. Wenn nicht stelle ich nochmal eine neue Beta bereit, glaube aber nicht, dass es daran liegt.

Danke
Markus

**Comment by DerDoubleD** [comment]
Hallo mackshot,

der Fehler mit dem Zeilenumbruch bzw. das nicht alles Zeichen dargestellt
wurden ist behoben.
Tolle Arbeit und vielen Dank für deine Mühe!
Ich hoffe der Fix wandert auch in den original Skin.

Gruß
Daniel


Am Do., 14. Mai 2020 um 21:22 Uhr schrieb Markus Pullmann <
notifications@github.com>:
