### ISSUE TITLE
FHEM startet von selbst neu/nicht steuerbar

### ISSUE THREAD

**Issue by Chuckwallas** [klein0r/fhem-style-haus-automatisierung#133]
Hallo,
ich habe das Problem, dass mein FHEM nach Änderung auf den Style garnicht mehr steuerbar ist. Es startet von allein neu, in unregelmäßigen Abständen (wenige Sekunden) und die Räume sind nicht mehr anwählbar.  Den Style kann ich nur über die fhem.conf rückgängig machen, durch manuelles anpassen. Dann funktioniert auch wieder alles.

Die Logfile ist bis oben hin gefüllt mit den folgenden, immer wiederkehrenden Zeilen:

2020.03.31 14:03:17 1: Including fhem.cfg
2020.03.31 14:03:17 3: WEB: port 8083 opened
2020.03.31 14:03:17 2: eventTypes: loaded 202 events from ./log/eventTypes.txt
2020.03.31 14:03:18 3: myBroker: port 1883 opened
2020.03.31 14:03:18 1: Including ./log/fhem.save
2020.03.31 14:03:18 2: alexa: starting alexa-fhem: /usr/bin/alexa-fhem -c ./alexa-fhem.cfg -a xx:xx -s
2020.03.31 14:03:18 3: alexa: starting
2020.03.31 14:03:18 3: alexa: using logfile: ./log/alexa-2020-03-31.log
2020.03.31 14:03:18 1: usb create starting
2020.03.31 14:03:19 3: Probing ZWDongle device /dev/serial1
2020.03.31 14:03:19 3: Probing CUL device /dev/ttyAMA0
2020.03.31 14:03:19 3: Probing TCM_ESP3 device /dev/ttyAMA0
2020.03.31 14:03:19 3: Probing ZWDongle device /dev/ttyAMA0
2020.03.31 14:03:19 3: Probing SIGNALDuino device /dev/ttyAMA0
2020.03.31 14:03:19 3: Probing MYSENSORS device /dev/ttyAMA0
2020.03.31 14:03:20 3: Probing ArduCounter device /dev/ttyAMA0
2020.03.31 14:03:20 3: Probing ElsnerWS device /dev/ttyAMA0
2020.03.31 14:03:21 3: Probing FRM device /dev/ttyAMA0
2020.03.31 14:03:21 1: usb create end
2020.03.31 14:03:21 0: Featurelevel: 6
2020.03.31 14:03:21 0: Server started with 29 defined entities (fhem.pl:21524/2020-03-27 perl:5.028001 os:linux user:fhem pid:16139)
2020.03.31 14:03:21 2: AttrTemplates: got 154 entries
Unmatched ( in regex; marked by <-- HERE in m/^transform="translate( <-- HERE -4.000000,$/ at ./FHEM/01_FHEMWEB.pm line 2917.

Eventuell hat es auch damit was zu tun?
2020.03.31 14:22:29 1: PERL WARNING: Use of uninitialized value in concatenation (.) or string at (eval 162) line 1. 

Ich bin leider ein absoluter FHEM Neuling und hangel mich von Anleitung zu Anleitung, aber dabei hätte ich gern deinen Style. :D

Vielen Dank im Voraus, vg

**Comment by mackshot** [comment]
Hallo @Chuckwallas,
spontan sehe ich da jetzt noch nichts, was darauf hindeutet. dass dies am Theme liegt. Endet das Log dort bzw. beginnt dann wieder mit `Including fhem.cfg` ?
Besteht das Problem überhaupt noch oder hat jetzt so lange keiner geantwortet, dass das Problem sich erledigt hat ;) ?
Grüße
Markus

**Comment by klein0r** [comment]
Der Style besteht eigentlich nur aus HTML, JS und CSS. Wie @mackshot schon geschrieben hat, kann der Fehler also nicht vom Theme ausgehen. Das ist nur die Darstellung, aber keine Logik.
