### ISSUE TITLE
Keine Icons bei Subrooms

### ISSUE THREAD

**Issue by lukeman11** [klein0r/fhem-style-haus-automatisierung#134]
Icons werden nicht angezeigt, wenn man versucht sie einem "Dropdown-Raum" zuzuweisen.

**Beispiel:**
`attr WEB roomIcons Räume->Kinderzimmer:scene_childs_room Räume->Küche:hue_room_kitchen Räume->Schlafzimmer:scene_making_love`

![Raeume](https://user-images.githubusercontent.com/19224685/78421311-d28de100-7656-11ea-93c4-a486c653001f.jpg)

**Comment by ftrojahn** [comment]
Hi, 

hatte das Problem letztens auch - aber dann las ich, dass das per regex funktioniert. 

Verwende es daher nun so:

```
Haus.*Waschkeller:control_building_kg Haus.*Flur:scene_stairs 
OG.*Büro:scene_office OG.*Bad:scene_bathroom OG.*(links|mitte):scene_livingroom
```
usw.

![fhem-theme-menu](https://user-images.githubusercontent.com/6184818/78544559-9c896200-77fa-11ea-815e-e011e664e8c8.jpg)

Nun fehlt mir leider nur noch die Idee, wie ich die Menüeinträge manuell sortieren kann statt alphabetisch ...

**Comment by flummy1978** [comment]
> Nun fehlt mir leider nur noch die Idee, wie ich die Menüeinträge manuell sortieren kann statt alphabetisch ...

Das geht ja ganz normal über das Attribut sortRooms in dem jeweiligen WEB device. Das ist unabhängig vom Style ;)

**Comment by ftrojahn** [comment]
> Das geht ja ganz normal über das Attribut sortRooms in dem jeweiligen WEB device. Das ist unabhängig vom Style ;)

Danke für den Hinweis. Das hatte bei mir eben nicht funktioniert - also sortRooms DG OG EG usw. 

Aber ich hab es jetzt nochmal mit DG->Bad OG->Bad OG->Büro usw. probiert, damit geht es nun.

**Comment by klein0r** [comment]
Genau, der Raum heißt dann wirklich ```DG->Bad``` in deinem Beispiel. Weder ```DG``` noch ```Bad``` ist ein einzelner Raum. **Es gibt keine Hierarchie oder ähnliches.** FHEMWEB zerlegt den Namen einfach nur am ```->```. Dennoch heißt er genau so und muss auch so angegeben werden. Diese Darstellung untereinander ist also eher ein Workaround über den Raumnamen.
