### ISSUE TITLE
Dashboard wird nicht mehr korrekt angezeigt

### ISSUE THREAD

**Issue by Dlay2017** [klein0r/fhem-style-haus-automatisierung#135]
Scheint als ob ein Umbruch fehlt
![image](https://user-images.githubusercontent.com/26193050/81875554-cd3e8300-9580-11ea-8f27-f8289b9b4841.png)

**Comment by klein0r** [comment]
@mackshot Guck, irgendwo fällt dann immer was hinten rüber 😄

**Comment by mackshot** [comment]
@Dlay2017 Kannst Du mir etwas besser erklären, wie es vorher aussah bzw. aussehen soll - ist mir leider nicht klar? Danke. Ich präzisiere meine Frage mal... ist es nicht eher so, dass hier jetzt ein Zeilenumbruch zu viel ist, der zuvor da nicht war? Konkreter, sollte zwischen Icon und Text der Umbruch nicht verschwinden?
@klein0r War ja klar ;)

**Comment by mackshot** [comment]
@Dlay2017 Ich habe mal eine BetaVersion aufgesetzt, die das Problem fixen sollte. Magst Du Dir das mal ansehen? Installationanleitung etc. findest Du [hier](https://github.com/mackshot/fhem-style-haus-automatisierung)

**Comment by Dlay2017** [comment]
> @Dlay2017 Kannst Du mir etwas besser erklären, wie es vorher aussah bzw. aussehen soll - ist mir leider nicht klar? Danke. Ich präzisiere meine Frage mal... ist es nicht eher so, dass hier jetzt ein Zeilenumbruch zu viel ist, der zuvor da nicht war? Konkreter, sollte zwischen Icon und Text der Umbruch nicht verschwinden?
> @klein0r War ja klar ;)

Gern, vorher sah es so aus.
![image](https://user-images.githubusercontent.com/26193050/81914583-c7bd5900-95d1-11ea-84eb-92191b966726.png)

Ich werde die neue Version testen. 
Vielen Dank für deine Mühe!

**Comment by Dlay2017** [comment]
@mackshot 
Also wenn ich die Dashboard Tab Groups breiter ziehe, dann geht es zwar mit der Formatierung, aber das ganze Dashboard wird dadurch richtig hässlich.
Früher ist diese Linie stehen geblieben, egal wie breit man das Tab gezogen hat. Jetzt bewegt sie sich aber mit, so dass Icon und Beschriftung nicht mehr genug Platz haben und dadurch natürlich einen Zeilenvorschub machen müssen um überhaupt angezeigt zu werden.
Das Problem ist also der "Trennstrich": 
![image](https://user-images.githubusercontent.com/26193050/81915484-ec660080-95d2-11ea-8a6c-65ae9999d001.png)

Die neue Version verhält sich gleich.

**Comment by mackshot** [comment]
Ich habe nochmal eine neue Beta bereitgestellt 2.17b3. Ich hoffe ich habe das richtig verstanden und jetzt nicht mehr kaputt als ganz gemacht ;) ... have a look, please! `update all ha_theme_mackshot`

**Comment by Dlay2017** [comment]
Leider krieg ich das nach deiner Anleitung nicht installiert :-(
Er lädt nur eine controls.txt runter, sonst nichts.
![image](https://user-images.githubusercontent.com/26193050/81980207-77c0af80-962e-11ea-85d6-9b40f1aeb54a.png)

In den Styles taucht der Fork nicht auf:
![image](https://user-images.githubusercontent.com/26193050/81980264-92932400-962e-11ea-82f7-7fbd8e86348b.png)

**Comment by Dlay2017** [comment]
Ich habe noch ein Video von dem Unterschied gemacht:

[Home, Sweet Home - Google Chrome 2020-05-14 22-07-59.zip](https://github.com/klein0r/fhem-style-haus-automatisierung/files/4630637/Home.Sweet.Home.-.Google.Chrome.2020-05-14.22-07-59.zip)

**Comment by mackshot** [comment]
Ich hatte leider noch einen Fehler in der URL ... bitte führe folgende Befehle aus:

`update remove https://raw.githubusercontent.com/klein0r/fhem-style-haus-automatisierung/version-2/controls_ha_theme_mackshot.txt`

`update add https://raw.githubusercontent.com/mackshot/fhem-style-haus-automatisierung/version-2beta/controls_ha_theme_mackshot.txt`

Dann sollte es gehen :)

Danke für das Video. Ich glaube ich habe jetzt sogar noch etwas verbessert was der original-Theme auch schon nicht optimal gemacht hat. Aber schau Dir bitte einfach mal die Beta jetzt an. Danke!

**Comment by Dlay2017** [comment]
Das Remove funktioniert leider nicht, kann ich das manuell löschen ?

Ok, der Befehl ist falsch, er muss update delete http://usw. lauten. Danach funktioniert es..
Ich habe das Theme getestet und jetzt funktioniert alles einwandfrei.

Vielen Dank für deine Mühe!!

**Comment by mackshot** [comment]
Mach doch bitte mal ein `update list`. Dann solltest Du alle externen Update-Quellen sehen. Dann kannst Du mit update remove jede löschen, die Du nicht mehr brauchst.

Ansonsten (aber ohne Gewähr!) kannst Du fhem beenden und dann im Installationsorder FHEM die Datei controls.txt bearbeiten.
