### ISSUE TITLE
modul weekprofile (98_weekprofile.pm) zeigt Kopieren, Bearbeiten, Zuweisen nicht an

### ISSUE THREAD

**Issue by hologramm077** [klein0r/fhem-style-haus-automatisierung#14]
Hallo Matthias,

bei der 98_weekprofile.pm (welche bei mir fehlerfrei läuft) werden in deinem Skin die (+) ( -)( -->) Buttons nicht angezeigt.
vgl. https://wiki.fhem.de/w/images/c/cf/Weekprofile_master.png (oben links)

+ (+) und (-) sind mir derzeit egal (meins is ja Fertig) aber --> sendet an die devices, das ist also UNBEDINGT nötig!

![hcs_bug](https://user-images.githubusercontent.com/22640740/29524994-9d0743b2-8691-11e7-8e41-aed5b573b7bb.png)

EDIT: Liegt definitiv an deinem JavaScript. Nach deaktivierung funzt es wieder.
Bin jetzt wieder auf fhem-dark.
Schade, war ein schöner Skin. 
P.S.:Mit codemirror/fhem_codemirror.js funktioniert alles noch ^^

**Comment by klein0r** [comment]
Mh ja okay, ich räume mit dem JavaScript die extrem miese HTML-Struktur von FHEM etwas auf. Daher passieren dann wohl teilweise komische Dinge. Muss ich mir noch einmal genauer anschauen.

**Comment by xXSTrikeXx** [comment]
Kann ich nicht bestätigen, bei mir läuft's. Ruf mal nen update auf ;)
