### ISSUE TITLE
2.17 zerfleddert Content Bereich (rechte Seite) u.a.

### ISSUE THREAD

**Issue by reibuehl** [klein0r/fhem-style-haus-automatisierung#146]
Ich hab gerade die 2.17 ausprobiert und bin geschockt vom ganzen aussehen. Bei Räumen mit mehreren Gruppen (attr group) werden die Gruppen mit unterschiedlicher Breite angezeigt, was die gesamte Darstellung zerfleddert. Außerdem wird die Eingabezeile in Seitenbreite ganz am oberen Rand noch über dem Logo angezeigt. Ist das ein Bug oder ein Feature?
Ich hab nach 2 Minuten einen Restore auf die vorherige Version gemacht....

**Comment by klein0r** [comment]
Ich habe einen Pull Request von @ole1986 angenommen - das ist das Ergebnis. 😭

**Comment by reibuehl** [comment]
Also wenn es geht, solltest Du den wieder raus machen... das Ergebnis ist echt eine Katastrophe.

**Comment by ole1986** [comment]
Master branch, nicht den pr

**Comment by meier81** [comment]
Also ich muss leider auch sagen das ich heute morgen das Update mit lauter Vorfreude installiert habe, sind ja doch immer wieder Verbesserungen drin. Von daher erstmal vielen Dank für die Arbeit die du hier reinsteckst.
Als ich dann aber den Browser aktualisiert hatte muss ich sagen bin ich auch erschrocken, das aussehen des Menüs hat sich etwas geändert, ist aber soweit okay. Wie mein Vorredner schon sagte ist die Eingabezeile jetzt ganz oben über die gesamte Breite, gefällt mir nicht so wirklich ist aber Geschmackssache. Was mich wirklich stört ist das Logfenster fängt jetzt erst unterhalb des Menüs an und nicht wie vorher oben am Seitenanfang, zudem sind alle Gruppen unterschiedlich breit. Im Raum sind diese zwar gleich breit, ich habe jetzt aber Einträge wie den Spritpreis, da ist das Feld gerade noch 2cm breit. Finde ich nicht wirklich gut.
Vielleicht sollte man überlegen ob manche Sachen wieder zurückgenommen werden.

**Comment by ole1986** [comment]
@meier81 screenshots?

Das mit der Logfile hängt leider bisher vom inhalt ab. Sofern dieser absolute kein leerzeichen beinhaltet bricht der inhalt nach unten. Ich werde das prüfen

**Comment by ReviloEgros** [comment]
Ich hatte den Fork zum responsive design aus dem Forum auch schon ausprobiert und gleich wieder gelöscht. Sagt mir so gar nicht zu. Schade. Also auch erstmal wieder ein restore machen.

**Comment by meier81** [comment]
Bin auch wieder zurück zur 2.16, ist so leider nichts für mich.

**Comment by meier81** [comment]
Hier noch ein paar Screenshots von der 2.16 (alt) und der neuen 2.17 (neu).
Ich glaube man kann die Unterschiede bzw. Probleme gut erkennen.

Logfile alt:
![Logfile alt](https://user-images.githubusercontent.com/40598096/105324520-d3830580-5bcb-11eb-9f81-1c8f35ffe0f7.JPG)

Logfile neu:
![Logfile neu](https://user-images.githubusercontent.com/40598096/105324541-d978e680-5bcb-11eb-8add-1a13f35cd1d1.JPG)

Einträge im Raum alt:
![Raumeinträge alt](https://user-images.githubusercontent.com/40598096/105324556-dd0c6d80-5bcb-11eb-8598-2ad2db24a6af.JPG)

Einträge im Raum neu:
![Raumeinträge neu](https://user-images.githubusercontent.com/40598096/105324562-e0075e00-5bcb-11eb-8093-b436b1752373.JPG)

Ansicht des Save Konfig-Buttons alt:
![Ansicht ungespeicherte Änderung alt](https://user-images.githubusercontent.com/40598096/105324590-e7c70280-5bcb-11eb-8fe5-a46b17d2ea30.JPG)

Ansicht des Save Konfig-Buttons neu:
![Ansicht ungespeicherte Änderung neu](https://user-images.githubusercontent.com/40598096/105324597-e990c600-5bcb-11eb-8aa8-3309e35b3162.JPG)

Und noch ein Bild vom neuen Menü und der Eingabeleiste ganz oben:
![Aussehen neu](https://user-images.githubusercontent.com/40598096/105324620-eeee1080-5bcb-11eb-86ed-e1812b75d254.JPG)

**Comment by ole1986** [comment]
@meier81  vielen dank für die konstruktive Kritik

Könntest du noch einen Screenshot posten, mit devices die ein oder mehrere funktionen aufweisen?
Z.b. ROLLO (Runter/hoch/...) oder Lichtschalter, etc...

Vielen Dank im voraus

**Comment by klein0r** [comment]
Die Frage ist, wie wir hier weiter machen. Sonst muss ich eine 2.18 bauen, welche identisch zu 2.16 ist.
Den Style haben hunderte Leute installiert und überall geht es gerade kaputt 😢

**Comment by reibuehl** [comment]
> Sonst muss ich eine 2.18 bauen, welche identisch zu 2.16 ist.

Ja, bitte!

**Comment by PureSecDE** [comment]
Fehler passieren, kein Problem.

Aber eine doofe Frage, wird so etwas vor einem neuen Release nicht getestet und die korrekte Anzeige geprüft?
Oder liegt es evtl. am Browser und mit dem "richtigen" Browser wird es korrekt angezeigt?

Ich habe den Edge und den Firefox geprüft, beides unschön, wie in den Screenshots von meier81 zu sehen.

**Comment by klein0r** [comment]
Habe 2.18 freigegeben.

@PureSecDE Ich selbst stecke hier keine Entwicklungszeit mehr rein. Deswegen war das etwas halbherzig getestet à la wird schon gut gehen. Zumal in der Vergangenheit immer gute Änderungen eingereicht wurden. Ist dieses Mal halt schief gegangen und jetzt wieder in Ordnung.

**Comment by reibuehl** [comment]
Danke!!!

**Comment by ole1986** [comment]
Da sich @klein0r von diesem Projekt distanziert und unbekannt ist wann es ein nächstes update gibt. Würde ich euch bitten die aktuelle version von mir über den nachfolgenden Weg zu testen.

**Version 2.2.0**
```
update add https://raw.githubusercontent.com/ole1986/fhem-style-haus-automatisierung/master/controls_ha_theme_ole1986.txt
update check ha_theme_ole1986
update all ha_theme_ole1986
```

Somit kann auch nun schneller zwischen dem Original und meinen Anpassungen gewechselt werden.

**Zurück zum Original**
```
update check ha_theme
update all ha_theme
```

**Comment by klein0r** [comment]
@ole1986 Nur das control file zu trennen ist keine so gute Idee - dann geht bei einem `update all` alles durcheinander.
