### ISSUE TITLE
attr Auswahlliste: Wert wird nicht übernommen

### ISSUE THREAD

**Issue by Bloona** [klein0r/fhem-style-haus-automatisierung#149]
Hallo,
ich habe seit (etwa) gestern das Problem, dass bei der Auswahl eines Wertes für "attr" dieser nicht im Auswahlfeld angezeigt wird. Das Feld bleibt nach Auswahl leer.
![07-03-_2021_17-31-39](https://user-images.githubusercontent.com/80213124/110247182-3c9bbe00-7f6b-11eb-9190-b5fc3de2355c.jpg)
Nach einigen Sekunden erhalte ich noch eine "Connection Lost" Fehlermeldung von FHEM. Mit einem anderen Theme kann ich den Devices Attribute zuweisen.

**Comment by WolfS2711** [comment]
Ich habe das gleiche Problem seit gestern mit allen Browsern.
Nur die Standard-Styles funktionieren.

**Comment by Thomas4170** [comment]
Hallo Matthias, auch ich habe das gleiche Problem mit den Attributen, leider finde ich nicht die Erklärung wie man auf den Standardstyle wieder umstellt.

**Comment by noripman** [comment]
...habe genau das selbe Problem...

**Comment by treibbhaus** [comment]
Hallo, kann von hier das Selbe berichten.

**Comment by jfmennedy** [comment]
In den letzten Updates gab es Änderungen in 01_fhemweb.pm und fhemweb.js... Möglich, dass hier irgendwo etwas angepasst werden muss, damit es wieder läuft???

![2021_03_09_19_45_59_fhemweb js_better_attr_help_Forum_119165_mhop_fhem_mirror_33b72bf](https://user-images.githubusercontent.com/52569066/110521589-3266f480-8110-11eb-8ca6-2ad6373cc9b2.png)

**Comment by Tertius76** [comment]
Ich habe das gleiche Problem.

**Comment by jfmennedy** [comment]
LÖSUNG:

Ihr müsst in der hausautomatisierung_com.js die Zeilen 181 - 241 entweder auskommentieren oder löschen: 

 $('table.attributes .dname').click(function (e) {
        var deviceName = $(this).attr('data-name');
        var rowVal = $(this).text();

        addToToolbar(
            [
                "AttrVal('" + deviceName + "', '" + rowVal + "', '');",
                "[a:" + deviceName + ":" + rowVal + "]",
                "global:ATTR." + deviceName + "." + rowVal + ".*"
            ]
        );
    });

    // Group attributes
    var attrSelect = $('select.attr');
    var attrList = new Object();
    attrList['general'] = ['userattr', 'verbose', 'disable', 'useSetExtensions', 'setList', 'disabledForIntervals', 'showtime'];
    attrList['readings'] = ['userReadings',  'oldreadings', 'suppressReading', 'readingList'];
    attrList['msg'] = ['msgContactAudio', 'msgContactLight', 'msgContactMail', 'msgContactPush', 'msgContactScreen', 'msgParams', 'msgPriority', 'msgRecipient', 'msgRecipientAudio', 'msgRecipientLight', 'msgRecipientMail', 'msgRecipientPush', 'msgRecipientScreen', 'msgRecipientText', 'msgTitle', 'msgTitleShrt', 'msgType'];
    attrList['events'] = ['event-aggregator', 'event-min-interval', 'event-on-change-reading', 'event-on-update-reading', 'eventMap', 'timestamp-on-change-reading', 'setExtensionsEvent'];
    attrList['fhemweb'] = ['alias', 'comment', 'cmdIcon', 'devStateIcon', 'devStateStyle', 'group', 'icon', 'room', 'sortby', 'stateFormat', 'webCmd', 'webCmdLabel', 'widgetOverride'];
    attrList['floorplan'] = ['fp_arrange', 'fp_backgroundimg', 'fp_default', 'fp_noMenu', 'fp_roomIcons', 'fp_setbutton', 'fp_viewport'];
    attrList['database'] = ['DbLogExclude', 'DbLogInclude'];

    var optGroups = new Object();
    optGroups['device'] = $('<optgroup label="device"></optgroup>');
    for (var attrGroup in attrList) {
        optGroups[attrGroup] = $('<optgroup label="' + attrGroup + '"></optgroup>');
    }

    if (attrSelect) {
        // clear the original list
        var attributeOptionList = attrSelect.children();
        var selectedItem = attrSelect.find('option:selected');
        attrSelect.empty();

        // add attributes to predefined optgroups
        attributeOptionList.each(function(i, e) {
            var found = false;
            for (var attrGroup in attrList) {
                if (attrList[attrGroup].indexOf($(e).attr('value')) > -1) {
                    optGroups[attrGroup].append(e);
                    found = true;
                }
            }

            if (!found) {
                optGroups['device'].append(e);
            }
        });

        // add optgroups to select
        for (var optGroup in optGroups) {
            if (optGroups[optGroup].children().length) {
                attrSelect.append(optGroups[optGroup]);
            }
        };

        // select previously selected item
        selectedItem.prop('selected', true);
    }

**Comment by klein0r** [comment]
Das liegt daran, dass der FHEM-Core wohl auch auf die Idee gekommen ist, dass es cooler wäre die Attribute in der Liste zu gruppieren. Das macht der Style ja schon seit Jahren so. Allerdings kollidiert das nun mit der neuen Logik im Core.

Also habe ich (wie von @jfmennedy schon vorgeschlagen) das Feature komplett entfernt.

Siehe Version 2.19

**Comment by fkh-bims** [comment]
Irgendwas fehlt noch:

021.03.11 05:16:36.867 1 : Downloading https://raw.githubusercontent.com/klein0r/fhem-style-haus-automatisierung/version-2/controls_ha_theme.txt
2021.03.11 05:16:36.868 1 : 
2021.03.11 05:16:36.869 1 : ha_theme
2021.03.11 05:16:40.544 1 : UPD www/pgm2/hausautomatisierung_com.js
2021.03.11 05:16:40.545 1 : Got 8504 bytes for www/pgm2/hausautomatisierung_com.js, expected 10944
2021.03.11 05:16:40.546 1 : aborting.

**Comment by jfmennedy** [comment]
> Irgendwas fehlt noch:
> 
> 021.03.11 05:16:36.867 1 : Downloading https://raw.githubusercontent.com/klein0r/fhem-style-haus-automatisierung/version-2/controls_ha_theme.txt
> 2021.03.11 05:16:36.868 1 :
> 2021.03.11 05:16:36.869 1 : ha_theme
> 2021.03.11 05:16:40.544 1 : UPD www/pgm2/hausautomatisierung_com.js
> 2021.03.11 05:16:40.545 1 : Got 8504 bytes for www/pgm2/hausautomatisierung_com.js, expected 10944
> 2021.03.11 05:16:40.546 1 : aborting.

Du musst umswitchen auf Version 3:

update delete https://raw.githubusercontent.com/klein0r/fhem-style-haus-automatisierung/version-2/controls_ha_theme.txt
update add https://raw.githubusercontent.com/klein0r/fhem-style-haus-automatisierung/version-3/controls_ha_theme.txt
update check ha_theme
update all ha_theme

Oder Matthias pflegt die controls_ha_theme.txt noch in v2 ein...

**Comment by WolfS2711** [comment]
Sorry, aber die Version 3 funktioniert doch immer noch nicht mit den 
Attributen!

VG
Wolfgang


Am 11.03.2021 um 10:39 schrieb jfmennedy:

**Comment by jfmennedy** [comment]
Ja in der Tat.. Das Update hat Matthias für V2 gemacht, aber die controls_ha_theme.txt in v3 eingepflegt...

**Comment by klein0r** [comment]
> Sorry, aber die Version 3 funktioniert doch immer noch nicht mit den Attributen!

Die Version 3 ist ja auch noch gar nicht freigegeben und es wird nicht empfohlen die Version zu nutzen.

**Comment by klein0r** [comment]
> Du musst umswitchen auf Version 3:

Ab hier übernimmt @jfmennedy den Support für diese Tipps 😄

**Comment by jfmennedy** [comment]
;-) Ich dachte das wäre die letzte Version, da Du da die Korrektur gemacht hast :-)

**Comment by klein0r** [comment]
War im falschen Branch auf meinem Entwicklungs-System, als ich die controls-Datei neu erstellt habe 😢

**Comment by jfmennedy** [comment]
Jetzt also wirklich closed ;-)

**Comment by WolfS2711** [comment]
Die Version 2.19 funktioniert jetzt mit den Attributen!
Vielen Dank!

VG
Wolfgang


Am 11.03.2021 um 11:54 schrieb Matthias Kleine:
