### ISSUE TITLE
Dashboard Symbole sind falsch

### ISSUE THREAD

**Issue by Dlay2017** [klein0r/fhem-style-haus-automatisierung#15]
Im normalen Zustand die "Einstellungen" Schaltfläche.
Im "unlocked" Mode die restlichen Symbole.

Siehe Screenshots
![unbenannt2](https://user-images.githubusercontent.com/26193050/29540992-c7584810-86d1-11e7-971c-91d5abd7fae6.JPG)
![unbenannt](https://user-images.githubusercontent.com/26193050/29540993-c9353b16-86d1-11e7-86eb-50d7aefc86f1.JPG)

**Comment by klein0r** [comment]
Mh okay, ich nutze kein Dashboard daher ist es mir noch nicht aufgefallen. Schaue ich mir an!
