### ISSUE TITLE
Änderungen an FHEMWEB 

### ISSUE THREAD

**Issue by pumabaer** [klein0r/fhem-style-haus-automatisierung#154]
durch einige Änderungen an fhemweb ist der button zum löschen oder für die raw definition momentan "schwer" zu treffen.
bitte schau da mal drüber.
<img width="384" alt="Bildschirm­foto 2022-10-31 um 01 25 42" src="https://user-images.githubusercontent.com/30412987/198909629-76167363-80dc-47b5-8c35-95929395fc78.png">

**Comment by klein0r** [comment]
Ich bin seit fast 2 Jahren bei FHEM raus. Keine Lust mehr auf den Umgang.

https://haus-automatisierung.com/fhem/2021/01/16/fhem-warum-ich-keine-videos-mehr-mache.html

**Comment by pumabaer** [comment]
oh, alles klar. 
Den Beitrag hatte ich damals gar nicht gesehen. 
Aber vollkommen verständlich 

Dann nochmal vielen dank für die ganze Arbeit!
