### ISSUE TITLE
SVG Plot Dropdownmenü

### ISSUE THREAD

**Issue by Diggewuff** [klein0r/fhem-style-haus-automatisierung#16]
Das Dropdownmenü, welches erscheint wenn man auf einen der legendeneitäge eines SVG Plots klickt, erscheint immer am unteren rand der Seite und nicht mehr, wie in 2.0, in der nähe des SVG Plots.
Außerdem sind die Plots ohne weißen Hintergrund schlecht lesbar.
Wünschenswert währe ein Weiser Hintergrund und orangene Beschriftungen.
Danke für deine Arbeit.

**Comment by Tazzzilo** [comment]
Ich habe folgendes eingetragen in www/pgm2/hausautomatisierung_comsvg_style.css:
`svg text.ylabel,text.y2label { fill: #000; } `
`svg[id^='SVGPLOT_'] { background-color: #FFF; }`

Diese Zeile habe ich geändert in www/pgm2/hausautomatisierung_comsvg_style.css von:
`svg text.title { fill: #fff; font-size: 16px; text-transform: uppercase; letter-spacing: 10px; }`
zu:
`svg text.title { fill: #000; font-size: 16px; }`

Zusäztlich habe ich das in www/pgm2/hausautomatisierung_comstyle.css ergänzt:
`#content #pedit table.plotEditor { max-width: 1200px; width: 120% }`

**Comment by klein0r** [comment]
Von welchem Dropdown-Menu reden wir hier? Gibt es den Fehler noch in 2.4?
Warum löst 120% Breite das Problem?
