### ISSUE TITLE
Separates scrollen zwischen Sidebar und Content

### ISSUE THREAD

**Issue by Diggewuff** [klein0r/fhem-style-haus-automatisierung#17]
Ich meine das es in Safari mal möglich war, in Sidebar (Räume) und Contentbereich (Devices), separat zu scrollen.
Mittlerweile bewegen sich die Elemente immer synchron.
Mag Geschmacksache sein, aber da ich viele Räume habe, würde ich es besser finden wenn man wieder separat sollen könnte.

**Comment by klein0r** [comment]
Wird Geschmackssache sein, ja :) Unterschiedlich scollende Bereiche auf Webseiten ist für mich ein wenig wie in den 90ern 😄  Okay, das Standard-FHEM-Design hängt da ja auch noch rum. Aber ich werde es so lassen wie es jetzt ist, da ich es lieber mag.
