### ISSUE TITLE
FTUI zerschossen

### ISSUE THREAD

**Issue by accessburn** [klein0r/fhem-style-haus-automatisierung#18]
Nachvollziehen kann ich es nicht, aber wenn ich auf hausautomatisierung_com umgestellt habe ist die FTUI Oberfläche CSS-Seitig zerstört:

Vorher
![vorher](https://user-images.githubusercontent.com/980696/30325958-1c8215a4-97c7-11e7-89c9-1a1b0b94a5b6.JPG)

Nachher
![nachher](https://user-images.githubusercontent.com/980696/30325911-ebd7fd4c-97c6-11e7-89b2-5683647e2b75.JPG)

**Comment by klein0r** [comment]
Das macht eigentlich keinen Sinn. Die CSS-Dateien usw. sind komplett getrennt.
