### ISSUE TITLE
Überschrift über den Gruppen

### ISSUE THREAD

**Issue by Fl0ca** [klein0r/fhem-style-haus-automatisierung#19]
Hi Matthias, 
kannst du irgendwie ne Option Einbauen, um die Riesig geschriebenen Überschriften irgend wieder zurück zu schalten, benutzerdefiniert?

Einigen wird das gefallen, nur mir gefällt das ganz und garnicht :(

Grüße
Florian

**Comment by klein0r** [comment]
Wenn Du mir sagst wie ;)
Konfigurationen für CSS, welche per JS ausgewertet werden können auf jeder Seite zu machen... Schwierig.

Am besten eine eigene CSS-Datei anlegen und die Überschriften so formatieren wie sie dir gefallen
