### ISSUE TITLE
WEBphone optimized style missing

### ISSUE THREAD

**Issue by handy80** [klein0r/fhem-style-haus-automatisierung#2]
Hi Matthias,
Erstmal wieder ein dickes Lob für deine Videos, den Blog und diese kleine CSS-Geschichte hier. Könntest du noch etwas für die iphone Oberfläche anpassen? Ich kann dort nur den Google chrome benutzen, weil safari wegen des selbst erstellten certificats meinen WebServer nicht sicher findet. 
Im chrome stellt er auf jeden Fall mit deinem Stylesheet die seite wie auf einem großen Monitor dar und auch die Einzelnen Inhaltszeilen mit gelbem Hintergrund. 
Das wäre noch super.
Lieben gruss
Holger

**Comment by handy80** [comment]
![img_0827](https://cloud.githubusercontent.com/assets/16490823/21944055/63ea5fac-d9d4-11e6-96b3-ff2386fd8730.PNG)

**Comment by klein0r** [comment]
Ich arbeite aktuell an einer "sauberen" Version 2.0 auf SCSS-Basis. Also sehr viel strukturierter. Dabei kommt im zweiten Schritt auch eine responsive-Version rum. Also braucht man die verschiedenen Weboberflächen nicht mehr (nutze ich persönlich eh nie), da alles auf das aktuelle Endgerät angepasst wird.
