### ISSUE TITLE
Spalten haben keinen Abstand

### ISSUE THREAD

**Issue by Eistee82** [klein0r/fhem-style-haus-automatisierung#20]
Spalten die mit attr column im FHEMWEB definiert sind haben keinen Abstand sondern kleben direkt aneinander was unschön aussieht.
[Version: 2.2]
![unbenannt](https://user-images.githubusercontent.com/1881217/31078907-3b7ff22e-a784-11e7-9828-b69aa678247c.PNG)

**Comment by klein0r** [comment]
Ah okay, nutze ich aktuell gar nicht das Feature, daher ist es mir noch nicht aufgefallen 😄 
Schaue ich mir noch an

**Comment by QTreiber** [comment]
ich habe das Problem durch Ergänzen folgender Zeile in der Datei "**hausautomatisierung_comstyle.css**" gelöst: `table.column.tblcol_2 { margin-left:15px;}`

**Comment by DeeBee84** [comment]
Der Teil mit `table.column.tblcol_2 { margin-left:15px;}` bringt schon mal einen Abstand zwischen die beiden Spalten. Jedoch wird die zweite Spalte nicht oben bündig sondern mittig ausgerichtet. Sieht auch unschön aus.
@klein0r Kannst du zumindest schon mal den Teil mit `table.column.tblcol_2 { margin-left:15px;}` übernehmen? Sonst ist das nach jedem Fhem Update wieder überschrieben.

![2019-02-28 16_23_29-fhem_ logo](https://user-images.githubusercontent.com/48097038/53577498-12da8000-3b76-11e9-8922-2e5db10cdef8.png)

Grüße
Dirk

**Comment by MaikelR2018** [comment]
Ich würde es auch sehr begrüßen diesen Fehler zu beheben! in meiner Übersichtsseite setze ich sogar 3 Spalten ein und das sieht dann echt nicht mehr schön aus!
![Haus01](https://user-images.githubusercontent.com/44468777/54480104-e9338100-4824-11e9-9203-402ed85aebad.PNG)

**Comment by klein0r** [comment]
In 2.12 gefixt

**Comment by lakelounge** [comment]
Ich würde es schön finden, wenn die Spalteninhalte nicht auf "middle" ausgerichtet wären …
Also in der hausautomatisierung_comstyle.css anstelle von:
`caption, th, td { text-align: left; font-weight: normal; vertical-align: middle; }`
besser:
`caption, th, td { text-align: left; font-weight: normal; vertical-align: top; }`
oder hat das einen bestimmten Grund?!

Ansonsten großes Lob und vielen Dank für das Theme Matthias

**Comment by klein0r** [comment]
@lakelounge Das werde ich nicht machen :) Kannst Du aber in dein Custom CSS eintragen, das überschreibt dann die Theme Einstellungen

**Comment by lakelounge** [comment]
war nur ein Vorschlag :-) Danke für den Tipp mit der custom.css
