### ISSUE TITLE
Keine Installation möglich ..

### ISSUE THREAD

**Issue by DittelHome** [klein0r/fhem-style-haus-automatisierung#21]
Hallo,
der update check läuft einwandfrei durch.
Bei update all wird die größe der custom.js bemängelt.
IMHO muss die controls_ha_theme.txt mit den neuen größen der files gefüllt werden..

mfg
Klaus

**Comment by KAGS1** [comment]
Hallo
Ich habe das gleiche Problem. Offenbar hat sich die Grösse geändert:
von 1789 auf 2185 bytes (www/hausautomatisierung-com/custom.js)

Könntest du dies im TXT-File anpassen?

Ansonsten finde ich deine Arbeit sensationell!

mfg
Kuno

**Comment by Soc007** [comment]
Hallo,

das gleiche Problem habe ich auch.

Gruß

Soc007

**Comment by Soc007** [comment]
Jetzt geht es. Danke.
