### ISSUE TITLE
2.4 kleinere Bugs und Fragen

### ISSUE THREAD

**Issue by Soc007** [klein0r/fhem-style-haus-automatisierung#22]
Hallo Matthias,

ich habe soeben die 2.4 installiert und stelle fest, dass nun (egal welchen Style ich aktiviert habe) hinter den save config ein Warndreieck erscheint. (siehe Anhang). - (erledigt, mein Fehler)
Das sogar im Default der Eintrag "Theme Fehler melden (2.4)" erscheint verwundert mich etwas, da es so aussieht als ob du alle Style mit den zusätzlichen Daten gefüttert hast.

 
<img width="278" alt="bildschirmfoto 2017-10-14 um 15 40 05" src="https://user-images.githubusercontent.com/32736802/31576245-0ddc0e3a-b0f7-11e7-9ffd-44077daa0704.png">

**Comment by Soc007** [comment]
Ach ja und noch was.
Es verschiebt sich teilweise der Text. (Hier bei Everything).
<img width="1021" alt="bildschirmfoto 2017-10-14 um 15 48 59" src="https://user-images.githubusercontent.com/32736802/31576261-5e505114-b0f7-11e7-9c14-a9f6bcb274b3.png">

**Comment by Soc007** [comment]
Ok. Den Eintrag mit den Warndreieck habe ich jetzt verstanden das ich es mit den RoomIcons selber gesetzt habe... :-) 
Aber ein Warndreieck finde ich etwas erschreckend. Ein anderes Symbol wäre nicht so schlimm. :-)
Das das überall erscheint ist jetzt auch klar, da ich es ja bei WEB gesetzt habe.
Sorry für die schnelle Annahme das es sich hierbei um einen Fehler handelt.

**Comment by Soc007** [comment]
Commandref ist wirklich super aufgebaut.
Das Layout verstrubbelt sich aber ein wenig wenn ich auf "zum Anfang" tippe.
Vorher:
<img width="285" alt="bildschirmfoto 2017-10-14 um 16 07 19" src="https://user-images.githubusercontent.com/32736802/31576377-09c85260-b0fa-11e7-8699-6d7a682f6b8f.png">
Nachher:
<img width="292" alt="bildschirmfoto 2017-10-14 um 16 07 42" src="https://user-images.githubusercontent.com/32736802/31576378-1029aa6e-b0fa-11e7-9b23-171ba0cdb6c3.png">

**Comment by Soc007** [comment]
Woher kommt eigentlich die Versionsnummer? Vom hem update oder von Dir?
<img width="121" alt="bildschirmfoto 2017-10-14 um 16 41 39" src="https://user-images.githubusercontent.com/32736802/31576619-b1175cd8-b0fe-11e7-96d4-415edaaf1f87.png">
<img width="156" alt="bildschirmfoto 2017-10-14 um 16 42 01" src="https://user-images.githubusercontent.com/32736802/31576620-b5ea79ca-b0fe-11e7-8301-29cfa958b759.png">

**Comment by Soc007** [comment]
Nachtrag zum verschobenen Text.
Das ist schon im Default Style vorhanden. Auch dort nicht spaltengerecht.

**Comment by Soc007** [comment]
Wenn ich den Screen nach unten scrolle, dann wird Dein Logo teilweise überdeckt und die Command Line verschwindet.
Kann man das ändern?

**Comment by klein0r** [comment]
Viel auf einmal hier 😄 

- Theme Fehler melden und die Versionsnummer wird vom JavaScript hinzugefügt. Einfach aus dem Attribut "JavaScripts" das js von mir löschen und dann sind die Infos wieder weg.
- Das mit dem Logo verschieben ist Absicht, das steht immer oben links quasi
- Das HTML in der CommandRef ist total schlecht aufgebaut, daher habe ich kaum Chancen das richtig zu gestalten. Ist sehr sehr sehr gruselig alles in FHEMWEB
