### ISSUE TITLE
Text ist verschoben

### ISSUE THREAD

**Issue by DittelHome** [klein0r/fhem-style-haus-automatisierung#23]
Hallo, hier ein paar kleiner Sachen:

Bei Eingabe von version mit Hausautomationsstyle:
![grafik](https://user-images.githubusercontent.com/14176684/31805756-a65ceede-b563-11e7-91ea-52029010a10d.png)
Dark Style:
![grafik](https://user-images.githubusercontent.com/14176684/31805850-75c462ec-b564-11e7-8c52-65d13f496773.png)

Bei Eingabe von info mit Hausautomationsstyle:
![grafik](https://user-images.githubusercontent.com/14176684/31805788-f317fba6-b563-11e7-891a-0bc72a3fc3dc.png)
Dark Style:
![grafik](https://user-images.githubusercontent.com/14176684/31805864-914ac614-b564-11e7-9289-5f5bf486cc8c.png)

Darstellung ReadingsGroup mit Hausautomationsstyle:
![grafik](https://user-images.githubusercontent.com/14176684/31805829-474c023a-b564-11e7-9442-85a3e43bb1e5.png)
Dark Style:
![grafik](https://user-images.githubusercontent.com/14176684/31805888-b03322ce-b564-11e7-881c-7d36aaaf752b.png)

Wenn mehr Information gebraucht wird, no Problem...
Ansonsten bin ich top zufrieden, DANKE

VG
Klaus Voigt

**Comment by klein0r** [comment]
Super, danke! Ist in 2.5 behoben 😄
