### ISSUE TITLE
Weiße Farbe bei Überschriften ReadingsGroup

### ISSUE THREAD

**Issue by CobraCane** [klein0r/fhem-style-haus-automatisierung#24]
Hallo Matthias,

bei mir kommt es zB. bei Überschriften von Readingsgroups dazu dass diese nicht zu sehen sind weil die Schrift weiß ist.
![bildschirmfoto 2017-10-28 um 12 59 09](https://user-images.githubusercontent.com/21129210/32133824-deda7100-bbdf-11e7-895a-da9705792fde.png)

Wenn man es mit der Maus markiert sieht man dass an der leeren Stelle "Fensterstatus" steht.

![bildschirmfoto 2017-10-28 um 13 04 56](https://user-images.githubusercontent.com/21129210/32133864-afd3e70a-bbe0-11e7-87a2-c77141326bb4.png)

**Comment by klein0r** [comment]
Danke, ist in 2.5 gelöst (Update kommt die Tage)
