### ISSUE TITLE
Save config Symbol verschwunden seit letztem fhemweb-update

### ISSUE THREAD

**Issue by binford6000** [klein0r/fhem-style-haus-automatisierung#25]
Seit dem letztem fhemweb-update ist das Save config Symbol verschwunden. Bei einer Änderung erschein nur der Rahmen, das Icon bleibt weiterhin  verschwunden.
![save_config_icon1](https://user-images.githubusercontent.com/29679540/32141556-d8788622-bc83-11e7-8857-9bc2ec50f240.png)
![save_config_icon](https://user-images.githubusercontent.com/29679540/32141557-d892c12c-bc83-11e7-9d33-89c0a2146006.png)

**Comment by herbert56** [comment]
Habe das Theme gerade erst neu installiert und habe das gleich Problem.

**Comment by Whilk-and-Misky** [comment]
Ebenfalls ist das Steckersymbol "plug" seit dem o.g. Update verschwunden.

**Comment by xXSTrikeXx** [comment]
Geht auf Web und ändert das Attribut roomIcon von "Save config:message_attention" auf "Save.config:message_attention". Der Punkt ist bei Leerzeichen wichtig ;)
