### ISSUE TITLE
Gruppen und Plots

### ISSUE THREAD

**Issue by absNoobalo** [klein0r/fhem-style-haus-automatisierung#27]
Wenn Plots zu Gruppen hinzugefügt werden verschwindet die "Statusleiste" -> Plots lassen sich nicht mehr bearbeiten.

Des weiteren ändert sich die Hintergrundfarben der restlichen Geräte in der Gruppe.

Vor Plot in Gruppe
![nogroup](https://user-images.githubusercontent.com/5582789/32242922-53f0abda-be74-11e7-9a6c-f8f484644634.jpg)

Plot in Gruppe
![group](https://user-images.githubusercontent.com/5582789/32242930-5c0b749e-be74-11e7-8b17-0154eef4f516.jpg)

**Comment by klein0r** [comment]
Dafür kann ich leider nichts, das ist FHEM-Standard.
