### ISSUE TITLE
maininput und Schaltflächen unten transparent

### ISSUE THREAD

**Issue by ManfMert** [klein0r/fhem-style-haus-automatisierung#3]
Nach Installation und Aktivierung ist "maininput" transparent. "maininput" definiert keine eigene Hintergrundfarbe, scheint aber auch kein zu erben.

input.maininput {
    width: 200%; <= Breite schon angepasst
}

Die Schaltflächen im unteren Bereich (Icon, Extend devStateIcon, ...) sind ebtnfalls transparent, also ohne weißen Hintergrund!?

![fhem maininput](https://cloud.githubusercontent.com/assets/24528404/22463174/cc39cd2e-e7b0-11e6-817a-59d99d1b3b96.JPG)
![fhem schaltflachen](https://cloud.githubusercontent.com/assets/24528404/22463175/cc3b0c0c-e7b0-11e6-89b7-2e82f1dcdcb6.JPG)

**Comment by Stinky78** [comment]
Um den Hintergrund bei den unteren Schaltflächen auch auf weiss zu ändern, mache folgendes im css:

.detLink {
    background-color: #FFFFFF;
    padding: 2px 10px;
    border: 2px #e56524 solid;
    border-radius: 0;
    margin-right: 0 !important;
}

**Comment by klein0r** [comment]
Das ist Absicht :) Aber gefällt mir auch noch nicht 100%ig.
Wird sich in Zukunft also noch ändern.
