### ISSUE TITLE
webCmd hue regler bleibt weiß

### ISSUE THREAD

**Issue by flolee** [klein0r/fhem-style-haus-automatisierung#30]
webCmd  bri funktioniert, aber bei webCmd hue und ct fehlt der farbverlauf im regler. V2.4, neu installiert.

danke für die ganze arbeit!!

![skizze fhem](https://user-images.githubusercontent.com/26747960/32410244-2cc02914-c1bc-11e7-8d3a-6f571e5a09d2.png)

**Comment by urmel86** [comment]
Ich habe das in der hausautomatisierung_comstyle.css in Zeile 79:
#content table .slider { width: 150px; }
so ergänzt:
#content table .slider { width: 150px; background: url(../jscolor/hue_background.svg); background-size: 150px;}

damit sehe ich wieder den Hintergrund in der richtigen Größe.
Nebeneffekte konnte ich auf die Schnelle keine entdecken.

Auch von mir ein großes Danke für die Arbeit mit dem Style!

**Comment by flolee** [comment]
@urmel86 Super, danke dir... das scheint zu klappen!! hätte man eigentlich auch selbst draufkommen können 👍

**Comment by urmel86** [comment]
@flolee Moin, habe grade gesehen, dass das nocht nicht 100% passt. Andere Slider haben jetzt auch den farbigen Hintergrund :-(

**Comment by flolee** [comment]
@urmel86 haha, danke... das gleiche ist mit gestern abend auch aufgegallen. vielen dank, so klappts jetzt!!

**Comment by klein0r** [comment]
Danke, ist in der nächsten Version enthalten
