### ISSUE TITLE
Hintergrundbild deaktivieren

### ISSUE THREAD

**Issue by Ulli2k** [klein0r/fhem-style-haus-automatisierung#31]
Gibt es eine Möglichkeit das Hintergrundbild bg_wrapper.jpg dauerhaft zu deaktivieren.
Ich lösche es aktuell nach jedem update...

**Comment by klein0r** [comment]
Nur mit einer eigenen CSS-Datei, welche entsprechend background auf none !important setzt.

**Comment by Ulli2k** [comment]
Das klappt leider nicht.
Ich habe folgendes gemacht.

attr WEB CssFiles myStyle.css
und in myStyle.css folgendes ergänzt
body { 
        background: #354d69 none !important no-repeat center 0 fixed;
        background-image: none !important;
}
