### ISSUE TITLE
Navigationsleiste in Floorplan.css

### ISSUE THREAD

**Issue by FireFighter112WO** [klein0r/fhem-style-haus-automatisierung#33]
Hallo Matthias,

im Floorplan wird auf der linken Seite mein Grundriss angezeigt, jedoch kann ich von dort nicht wieder direkt zurück zu FHEM.

Lässt sich das einrichten oder musst du dazu die .css ändern?
![image](https://user-images.githubusercontent.com/33814175/32995599-3311f89e-cd77-11e7-9b7d-8e9f1347ec62.png)

**Comment by klein0r** [comment]
Geht das denn im Standard?!

**Comment by guen123** [comment]
Hi, hab' das gleiche Problem.
Es geht im Standard.

**Comment by klein0r** [comment]
Muss ich mir mal angucken. Der FHEM-Standard ist nach wie vor extrem gruselig (was Weboberflächen angeht) und ich kann mir nur an dem entlang hangeln, was ich auch zur Verfügung habe.
