### ISSUE TITLE
Save config:message_attention

### ISSUE THREAD

**Issue by knightxde** [klein0r/fhem-style-haus-automatisierung#34]
Wenn ich das Icon für "Save config" hinterlegen möchte, trage ich unter roomicon folgendes ein:
Save config:message_attention

Das funktioniert leider nicht. bei allen anderen Räumen klappt das. Kann es sich hier um einen Bug handeln?

Grüße, Knight

**Comment by knightxde** [comment]
Save.config:message_attention war die Lösung. Habe ich zu spät gesehen :)

**Comment by klein0r** [comment]
Genau, FHEM ist etwas strenger geworden :) Passe es in der Readme an. Danke!
