### ISSUE TITLE
EventMonitor in DOIFTools

### ISSUE THREAD

**Issue by trinitywhm** [klein0r/fhem-style-haus-automatisierung#36]
Hallo Matthias, in den DOIFTools kann man den Eventmonitor innerhalb den Tools ein- und ausschalten. Das EventMonitor-Fenster ist weiß und die Schrift dort ist leider ebenfalls weiß. Man erkennt erst dass es hier Einträge gibt, wenn man im vermeintlich leeren weißen Fenster markiert. Aber um eine Zeile rauszufinden und diese dann zu markieren ist das natürlich sehr ungünstig.

**Comment by xXSTrikeXx** [comment]
Untersuche die Stelle mal mit Firebug, vielleicht ist dies in eine css Klasse eingebunden, in der man die Schriftart ändern kann. Muss so etwas wie class=“ stehen.

**Comment by trinitywhm** [comment]
Es ist keine CSS-Klasse in der die Farbe weiß für die Schrift steckt, sondern eine textarea mit ID (<textarea title="Die Auswahl einer Event-Zeile zeigt Operanden für DOIF an, mit ihnen kann eine neue DOIF-Definition erzeugt werden." cols="60" rows="25" readonly="readonly" style="width:99%; top:.1em; bottom:1em; position:relative;" id="console"></textarea>)

**Comment by tb-killa** [comment]
Hallo Matthias,
Ich habe möglicherweise den Fehler gefunden (siehe Screenshot)
![unbenannt](https://user-images.githubusercontent.com/932481/35182439-66f08476-fdd5-11e7-93be-2672243506f2.jpg)

Kannst du dies bei Gelegenheit testen ?
Ich würde vorschlagen den Eintrag zu entfernen.
Gruß

**Comment by klein0r** [comment]
Ist in 2.6 behoben
