### ISSUE TITLE
SVG-Plot

### ISSUE THREAD

**Issue by Lazgar** [klein0r/fhem-style-haus-automatisierung#37]
Wenn man einen SVG-Plot einer group zuordnet werden diese und andere devices in der group nicht richtig dargestellt. Könnte auch so gewollt sein, sieht aber nicht besonders aus.

**Comment by Groepi** [comment]
Das Problem besteht ja schon länger und wir sollten es lt. Matthias auch ins 2.5 mit übernehmen.

Wenn man gruppiert sieht es einfach komisch aus. Auch das die Beschriftung nicht Orange ist sondern weiß. Die Skalenbeschriftung sollte schwarz bzw. dunkelgrau sein.

Und der Hintergrund hellgrau und weiß.

![fhem_group](https://user-images.githubusercontent.com/18686150/33806401-e4af74cc-ddc7-11e7-9a06-9b15a4c6eb5c.jpg)

Übrigens wenn im Web nur attr WEB JavaScripts codemirror/fhem_codemirror.js (also hausautomatisierung-com/custom.js wegläßt). Dann siehts besser aus nur kommt dann eine Fehlermeldung das mann das WEB anpassen soll.
![fm](https://user-images.githubusercontent.com/18686150/33806465-e7280768-ddc8-11e7-9bca-6212b3fa0282.jpg)

Aber die Übersicht sieht besser aus:

![fhem_group2](https://user-images.githubusercontent.com/18686150/33806468-f33c928a-ddc8-11e7-81a1-2adf240ec637.jpg)

Wenn die Beschriftung Orange und die Skala dunkelgrau / schwarz würde mann dann wieder alles lesen können und würde vor allem zur Logik passen.

Grüße

Gröpi

**Comment by fratzr** [comment]
Die Schrift wechselt zu Serif, sobald ein SVG-Plot angezeigt wird.

**Comment by Lazgar** [comment]
ETA?

**Comment by Magic01** [comment]
Das Problem von Groepi  habe ich auch, bei einer Gruppe habe ich plötzlich transparente Hintergründe bei Geräten.
Im Allgemeinen finde ich auch den transparente Hintergründe bei den Plots sehr störend.  Durch den bunten Hintergrund erkennt man an fast jeder beliebigen Stelle irgendeine Farbe im Plot nicht - Man muss also fast immer scrollen bis man alles erkennen kann. Also, entweder sieht man eine bestimme Farbe des Plots nicht oder die Grid Linien verschwinden. 
Für meinen Geschmack wäre es schöner, wenn auch die Plots, wie die Geräte mit einem einfarbigen Hintergrund hinterlegt wären.

**Comment by flipkill1985** [comment]
Hmm, das ist schon sehr störend. Wird das noch gefixxt?

**Comment by klein0r** [comment]
Ist in 2.6 behoben

**Comment by flipkill1985** [comment]
Und die bekomme ich wo?

**Comment by klein0r** [comment]
Immer mit der Ruhe 😄 
Gerade veröffentlicht, ahnt ja niemand dass ihr so schnell reagiert

**Comment by flipkill1985** [comment]
Funktioniert Danke :D
