### ISSUE TITLE
z-Wave, "Show neighbor map" wird nicht in der richtigen Grösse angezeigt

### ISSUE THREAD

**Issue by botpflanze** [klein0r/fhem-style-haus-automatisierung#38]

**Comment by botpflanze** [comment]
so sieht es aus
![grafik](https://user-images.githubusercontent.com/7704339/34319863-87a6ca62-e7ec-11e7-8cd5-4fb5b6780cb4.png)
und so sollte es sein
![grafik](https://user-images.githubusercontent.com/7704339/34319875-ca8e1f9c-e7ec-11e7-8fe5-28c637232961.png)

**Comment by botpflanze** [comment]
Sorry, (oh Hardware vor der Tastatur), ist mein erstes issue

**Comment by klein0r** [comment]
Ist in 2.6 behoben :)
