### ISSUE TITLE
Verschieben von Dialogboxen

### ISSUE THREAD

**Issue by jpawlowski** [klein0r/fhem-style-haus-automatisierung#4]
Hi Matthias,

ggf. kannst du das hier ja in einer der nächsten Iterationen berücksichtigen :-)
https://forum.fhem.de/index.php/topic,71714

VG
Julian

**Comment by klein0r** [comment]
Gute Idee 👍

**Comment by klein0r** [comment]
Kommt in 2.2 - wird bald freigegeben.
