### ISSUE TITLE
Hintergrund bei Readingsgroup

### ISSUE THREAD

**Issue by Hasenpups** [klein0r/fhem-style-haus-automatisierung#40]
Wenn die Readingsgroup breiter wird, ist der Hintergrund teilweise nicht mehr Weiß.

![readingsgroup](https://user-images.githubusercontent.com/29422053/35043547-4d411e2c-fb8d-11e7-84a5-310584a1bcb6.png)

**Comment by klein0r** [comment]
Oh, okay, so breite readingsGroups habe ich noch nicht angelegt :)
