### ISSUE TITLE
Uhrzeit im Style

### ISSUE THREAD

**Issue by RalphK1200LT** [klein0r/fhem-style-haus-automatisierung#43]
Hallo Matthias, ich hatte vor deinem Style immer über ein JavaScript eine Uhr eingebunden die dann links oben das normale FHEM Haus ersetzt hat. Könnte man etwas entsprechendes in deinen Style einbauen?

**Comment by klein0r** [comment]
Kannst Du doch nach wie vor auch noch machen, oder was spricht dagegen?

Ich finde Uhren auf Webseiten genauso überflüssig wie z.B. Besucherzähler - Du hast definitiv irgendwo anders auf deinem Bildschirm auch noch die Uhrzeit während Du auf der Seite bist, oder nicht?
