### ISSUE TITLE
SVG Farben der Füllung vertauscht

### ISSUE THREAD

**Issue by JoschaMiddendorf** [klein0r/fhem-style-haus-automatisierung#45]
Da ist wohl was durcheinander gekommen.
![bildschirmfoto 2018-02-04 um 01 41 06](https://user-images.githubusercontent.com/19818109/35773246-85076b5a-094c-11e8-9bc8-ec6565998647.png)
l0 -> Blaue Linie      -      l0fill -> Blaue Linie + Rote Füllung?
l0 -> Rote Linie        -     l0fill -> Rote Linie + Blaue Füllung?

habe nicht alle Kombinationen getestet, aber die sind schonmal verkehrt.

**Comment by klein0r** [comment]
Also ich finde die Bezeichnungen generell ziemlich strange.

Das jetzt zu tauschen würde bei vielen die Farben in den Plots auf einmal ändern, das möchte ich niemandem antun :)

**Comment by JoschaMiddendorf** [comment]
Die Linien würden ja gleich bleiben nur die Füllung würde wieder farblich passen wenn man fill angewählt hat. Derzeit gibt es keine Möglichkeit Füllungen zu generieren die auch zu den Linien passen.

**Comment by flummy1978** [comment]
Zunächst einmal vielen Dank für die Arbeit die Ihr in dieses Style steckt. Es ist wirklich ein tolles Design *thumbup* 

Ich würde das gerne nochmal aufgreifen wollen:
Wenn man verschiedene Farben auswählt, ist Füllung und vor allem aber die Linienfarbe unterschiedlich zum Standard. D.h. es ist bzw unmöglich für mehrere Styles (Mobil und PC) Farben einzustellen, die sich entsprchend unterscheiden.Die Screens sind jeweils als Vergleich mit dem Standardstyle
![screen1](https://user-images.githubusercontent.com/49339206/55668811-e994ca00-586e-11e9-9359-d0e756a330c6.jpg)
![screen2](https://user-images.githubusercontent.com/49339206/55668812-e994ca00-586e-11e9-939c-ef643ab2d262.jpg)

**Comment by JoschaMiddendorf** [comment]
Hey Matthias, 
grade dass die Füllung nicht der Linienfarbe entspricht ist manchmal schon echt Fummelig.

**Comment by JoschaMiddendorf** [comment]
Hey Matthias,
kannst du dir das Thema nicht doch vielleicht mal anschauen? 
Plots mit Füllungen sind so leider nicht mehr brauchbar und das ist schon echt schade.
Wenn du mir einen Hinweis gibst, wo ich eventuell selber Anpassungen am CSS vornehmen kann, würde ich mich das sonst auch mal einlesen, aber momentan stehe ich ein bisschen wie der Ochs vorm Berge.

Gruß Joscha

**Comment by klein0r** [comment]
@JoschaMiddendorf Ich selbst nutze halt kein SVG in FHEM - daher brennt das bei mir nicht so 😄Der Style wird mit scss/compass aus dieser Datei gebaut:

https://github.com/klein0r/fhem-style-haus-automatisierung/blob/version-2/sass/hausautomatisierung_comsvg_style.scss

**Comment by JoschaMiddendorf** [comment]
Wenn die Farben in der svg_defs.svg folgendermaßen angepasst werden stimmen die Füllfarben wieder mit den Linienfarben überein.
Da die Datei scheinbar nicht Bestandteil deines style sind, werden hier noch die alten Farbschemata verwendet.
`
<defs>
  <linearGradient id="gr_bg" x1="0%" y1="0%" x2="0%" y2="100%">
    <stop offset="0%"   style="stop-color:#FFFFF7; stop-opacity:1"/>
    <stop offset="100%" style="stop-color:#FFFFC7; stop-opacity:1"/>
  </linearGradient>

  <linearGradient id="gr_0" x1="0%" y1="0%" x2="0%" y2="100%">
    <stop offset="0%"   style="stop-color:#215A94; stop-opacity:.6"/>
    <stop offset="100%" style="stop-color:#215A94; stop-opacity:.4"/>
  </linearGradient>

  <linearGradient id="gr_1" x1="0%" y1="0%" x2="0%" y2="100%">
    <stop offset="0%"   style="stop-color:#18986E; stop-opacity:.6"/>
    <stop offset="100%" style="stop-color:#18986E; stop-opacity:.4"/>
  </linearGradient>

  <linearGradient id="gr_2" x1="0%" y1="0%" x2="0%" y2="100%">
    <stop offset="0%"   style="stop-color:#913100; stop-opacity:.6"/>
    <stop offset="100%" style="stop-color:#913100; stop-opacity:.4"/>
  </linearGradient>

  <linearGradient id="gr_3" x1="0%" y1="0%" x2="0%" y2="100%">
    <stop offset="0%"   style="stop-color:#915700; stop-opacity:.6"/>
    <stop offset="100%" style="stop-color:#915700; stop-opacity:.4"/>
  </linearGradient>

  <linearGradient id="gr_4" x1="0%" y1="0%" x2="0%" y2="100%">
    <stop offset="0%"   style="stop-color:#07325E; stop-opacity:.6"/>
    <stop offset="100%" style="stop-color:#07325E; stop-opacity:.4"/>
  </linearGradient>

  <linearGradient id="gr_5" x1="0%" y1="0%" x2="0%" y2="100%">
    <stop offset="0%"   style="stop-color:#006141; stop-opacity:.6"/>
    <stop offset="100%" style="stop-color:#006141; stop-opacity:.4"/>
  </linearGradient>

  <linearGradient id="gr_6" x1="0%" y1="0%" x2="0%" y2="100%">
    <stop offset="0%"   style="stop-color:#FFA77A; stop-opacity:.6"/>
    <stop offset="100%" style="stop-color:#FFA77A; stop-opacity:.4"/>
  </linearGradient>
  
  <linearGradient id="gr_7" x1="0%" y1="0%" x2="0%" y2="100%">
    <stop offset="0%"   style="stop-color:#5F8AB6; stop-opacity:.6"/>
    <stop offset="100%" style="stop-color:#5F8AB6; stop-opacity:.4"/>
  </linearGradient>

  <linearGradient id="gr_8" x1="0%" y1="0%" x2="0%" y2="100%">
    <stop offset="0%"   style="stop-color:#59B99A; stop-opacity:.6"/>
    <stop offset="100%" style="stop-color:#59B99A; stop-opacity:.4"/>
  </linearGradient>

  <pattern id="gr0_stripe" width="4" height="4"
           patternUnits="userSpaceOnUse" patternTransform="rotate(-45 2 2)">
      <path d="M -1,2 l 6,0" stroke="#215A94" stroke-width="0.5"/>
  </pattern>

  <pattern id="gr1_stripe" width="4" height="4"
           patternUnits="userSpaceOnUse" patternTransform="rotate(45 2 2)">
      <path d="M -1,2 l 6,0" stroke="#18986E" stroke-width="0.5"/>
  </pattern>

  <linearGradient id="gr0_gyr" x1="0%" y1="0%" x2="0%" y2="100%">
    <stop offset=  "0%" style="stop-color:#f00; stop-opacity:.6"/>
    <stop offset= "50%" style="stop-color:#ff0; stop-opacity:.6"/>
    <stop offset="100%" style="stop-color:#0f0; stop-opacity:.6"/>
  </linearGradient>

</defs>`

**Comment by JoschaMiddendorf** [comment]
Wenn die Farben in der svg_defs.svg folgendermaßen angepasst werden stimmen die Füllfarben wieder mit den Linienfarben überein.
Da die Datei scheinbar nicht Bestandteil deines style sind, werden hier noch die alten Farbschemata verwendet.

```
<!-- will be included in each svg plot -->
<defs>
  <linearGradient id="gr_bg" x1="0%" y1="0%" x2="0%" y2="100%">
    <stop offset="0%"   style="stop-color:#FFFFF7; stop-opacity:1"/>
    <stop offset="100%" style="stop-color:#FFFFC7; stop-opacity:1"/>
  </linearGradient>

  <linearGradient id="gr_0" x1="0%" y1="0%" x2="0%" y2="100%">
    <stop offset="0%"   style="stop-color:#215A94; stop-opacity:.6"/>
    <stop offset="100%" style="stop-color:#215A94; stop-opacity:.4"/>
  </linearGradient>

  <linearGradient id="gr_1" x1="0%" y1="0%" x2="0%" y2="100%">
    <stop offset="0%"   style="stop-color:#18986E; stop-opacity:.6"/>
    <stop offset="100%" style="stop-color:#18986E; stop-opacity:.4"/>
  </linearGradient>

  <linearGradient id="gr_2" x1="0%" y1="0%" x2="0%" y2="100%">
    <stop offset="0%"   style="stop-color:#913100; stop-opacity:.6"/>
    <stop offset="100%" style="stop-color:#913100; stop-opacity:.4"/>
  </linearGradient>

  <linearGradient id="gr_3" x1="0%" y1="0%" x2="0%" y2="100%">
    <stop offset="0%"   style="stop-color:#915700; stop-opacity:.6"/>
    <stop offset="100%" style="stop-color:#915700; stop-opacity:.4"/>
  </linearGradient>

  <linearGradient id="gr_4" x1="0%" y1="0%" x2="0%" y2="100%">
    <stop offset="0%"   style="stop-color:#07325E; stop-opacity:.6"/>
    <stop offset="100%" style="stop-color:#07325E; stop-opacity:.4"/>
  </linearGradient>

  <linearGradient id="gr_5" x1="0%" y1="0%" x2="0%" y2="100%">
    <stop offset="0%"   style="stop-color:#006141; stop-opacity:.6"/>
    <stop offset="100%" style="stop-color:#006141; stop-opacity:.4"/>
  </linearGradient>

  <linearGradient id="gr_6" x1="0%" y1="0%" x2="0%" y2="100%">
    <stop offset="0%"   style="stop-color:#FFA77A; stop-opacity:.6"/>
    <stop offset="100%" style="stop-color:#FFA77A; stop-opacity:.4"/>
  </linearGradient>
  
  <linearGradient id="gr_7" x1="0%" y1="0%" x2="0%" y2="100%">
    <stop offset="0%"   style="stop-color:#5F8AB6; stop-opacity:.6"/>
    <stop offset="100%" style="stop-color:#5F8AB6; stop-opacity:.4"/>
  </linearGradient>

  <linearGradient id="gr_8" x1="0%" y1="0%" x2="0%" y2="100%">
    <stop offset="0%"   style="stop-color:#59B99A; stop-opacity:.6"/>
    <stop offset="100%" style="stop-color:#59B99A; stop-opacity:.4"/>
  </linearGradient>

  <pattern id="gr0_stripe" width="4" height="4"
           patternUnits="userSpaceOnUse" patternTransform="rotate(-45 2 2)">
      <path d="M -1,2 l 6,0" stroke="#215A94" stroke-width="0.5"/>
  </pattern>

  <pattern id="gr1_stripe" width="4" height="4"
           patternUnits="userSpaceOnUse" patternTransform="rotate(45 2 2)">
      <path d="M -1,2 l 6,0" stroke="#18986E" stroke-width="0.5"/>
  </pattern>

  <linearGradient id="gr0_gyr" x1="0%" y1="0%" x2="0%" y2="100%">
    <stop offset=  "0%" style="stop-color:#f00; stop-opacity:.6"/>
    <stop offset= "50%" style="stop-color:#ff0; stop-opacity:.6"/>
    <stop offset="100%" style="stop-color:#0f0; stop-opacity:.6"/>
  </linearGradient>

</defs>
```
