### ISSUE TITLE
Plot Problem Form

### ISSUE THREAD

**Issue by Chris383838** [klein0r/fhem-style-haus-automatisierung#46]

**Comment by Chris383838** [comment]
![screenshot_2018-02-04-15-35-54-709_com android chrome](https://user-images.githubusercontent.com/22688323/35778697-2f7c5c7e-09c2-11e8-815e-8f81d3886f4f.png)

**Comment by Tazzzilo** [comment]
Gleiches Problem mit den Plot-Überschriften habe ich auf meinem Note 4 in Samsung Internet Browser und Opera, sowie auf dem Fire HD 8 Tablet in Opera. Nur im Firefox wird es korrekt dargestellt. 
Ich würde eine Änderung des Plot-Überschriften-CSS-Style befürworten.
