### ISSUE TITLE
Responsive Layout

### ISSUE THREAD

**Issue by andreschaefer** [klein0r/fhem-style-haus-automatisierung#48]
Vielen Dank für diesen schicken Style. 

Sehr cool wäre es, wenn man das ganze dahingehend optimieren könnte, dass er sich für kleine View-Ports automatisch optimiert.
 Cool wäre für kleinere View-Ports
- Off Screen Naviagtion (z.B. https://codepen.io/SitePoint/pen/uIemr)
- schmalerer content

**Comment by inconsx** [comment]
das wäre ein hit, vorallem fürs mobile!

**Comment by klein0r** [comment]
Ist aktuell nicht geplant, da es viel Zeit kosten würde und ich es selbst nie mobile nutzen würde. Ist eben nur eine Admin-Oberfläche für mich.

**Comment by TungstenE2** [comment]
@klein0r wäre toll wenn du den Fix aus dem Pull Request übernehmen würdest. Danke Dir

**Comment by digitalyours** [comment]
Interessehalber: Den PR hast du in der aktuellen Version wieder entfernt, oder?

**Comment by klein0r** [comment]
Ja, wurde in den Branch version-3 verschoben weil es bei mir das komplett Design kaputt gemacht hatte.
Scheinbar war der PR unvollständig.

**Comment by digitalyours** [comment]
Ok, Danke für die schnelle Rückmeldung. Bei mir funktioniert der Fork von Ole auf den iOS Geräten auch nur so halb.
