### ISSUE TITLE
Fehler beim Update

### ISSUE THREAD

**Issue by Hoockman** [klein0r/fhem-style-haus-automatisierung#49]
Ich habe in letzter Zeit immer folgenden Fehler beim Update:

https://raw.githubusercontent.com:443: Attempt to reload IO/Socket/SSL.pm aborted.
Compilation failed in require at (eval 25) line 2.
BEGIN failed--compilation aborted at (eval 25) line 2.

Wie kann ich diesen beheben?

**Comment by klein0r** [comment]
Eventuell gab es ein Problem bei GitHub mit der Verbindung. Ist ja auch schon sehr alt der Issue. Mache ich mal zu.
