### ISSUE TITLE
plots and "save config" icon

### ISSUE THREAD

**Issue by mopby** [klein0r/fhem-style-haus-automatisierung#5]
Servus Matthias, ich bin so frei und schreib dir einfach auf deutsch :)

ich habe deinen style von Anfang an und bin mehr als zufrieden, vielen Dank hierfür!

Ich habe gestern auf den 2.0er geupdatet und den alten Ordner mit der 1.2er Version vorher gelöscht.

Ich habe jetzt allerdings das Problem, dass ein Orangener Kasten um das Icon für "Save Config" exisiert. (siehe Bild)

Auch kann ich kein "Styling" mehr für die Linien im Plot auswählen (siehe Bild).

Beste Grüße,
Manu
![bildschirmfoto 2017-07-06 um 15 34 27](https://user-images.githubusercontent.com/16632477/27913529-b4ca7f28-6260-11e7-819d-f28a3b944eca.png)
![bildschirmfoto 2017-07-06 um 15 34 58](https://user-images.githubusercontent.com/16632477/27913534-b63de0ac-6260-11e7-84ae-5881b3bf2b00.png)

**Comment by Groepi** [comment]
Hallo Matthias,

ich kann mich dann nur anschließen das SVG ist generell noch "bugy". Die Überschriften sind weiß auf weißen Hintergrund. Und es wäre auch toll wenn die Farben geändert werden könnten. Auch die schrafierten oder durchscheinenden Graphen wären toll.
Ich habe Fühler für Feuchtigkeit und Temperatur. Hier wäre z.B, Rot und Blau intuitiver.

Aber ansonsten ist das Skin wirklich super!!!

Danke Gröpi

**Comment by fasv0002** [comment]
Hallo Matthias,

ich möchte mich hier auch anschließen! Top Style, aber die Graphen sind etwas unglücklich. Weisse Schrift auf weissen Hintergrund in Überschrift und Achsenbeschriftung wenn gruppiert wird sowie fehlende Transparenzîn der Graphen...
![screenshot_20170713-141815](https://user-images.githubusercontent.com/30148760/28166785-93e1886e-67d9-11e7-95d8-fa1b3670dc39.JPG)

Temporär habe ich die "ios7svg_style.css" in "hausautomatisierung_comsvg_style.css" umbenannt. So sieht es z.Z. so aus:
![grafik](https://user-images.githubusercontent.com/30148760/28166931-182d4b12-67da-11e7-9e8b-d24dfb7cba3e.png)

Ich hoffe dass bals eine "kleine" Anpassung erfolgt.... Ferner eine schöne Skalierung für Smartphone wäre Klasse.

LG
Sven

**Comment by klein0r** [comment]
Ist in 2.2 gefixt
