### ISSUE TITLE
Fehlermeldung unter der Eingabeleiste - !!! Bitte Theme-JS aktivieren für vollen Funktionsumfang...

### ISSUE THREAD

**Issue by Sonsi79** [klein0r/fhem-style-haus-automatisierung#50]
Hi
Danke für das coole Style. Gefällt mir sehr gut.

Leider sehe ich bei jedem **Seitenwechsel** und bei jedem ausgefüllten Befehl ganz **kurz für den Bruchteil einer Sekunde** direkt unter der Eingabeleiste die Meldung:
`!!! Bitte Theme-JS aktivieren für vollen Funktionsumfang: attr WEB roomIcons Save.config:message_attention`

Das Attr ist gesetzt und ich würde behaupten dass auch alles funktioniert.
Im Log sehe ich auch keine Einträge.

Dennoch nervt es tierisch, dass die Meldung kurz aufploppt und direkt verschwindet.
Getestet mit Safari (OSX) und Firefox.

Hat jemand eine Idee?

EDIT:
Zusätzlich tausch direkt auf der Startseite (Klick auf das Haus-Automatisierung Logo) unter der Eingabeleiste eine weiße "**1**"

**Comment by Sonsi79** [comment]
Beim "Update" sehe ich zudem noch diese Meldungen, nehme an es hängt zusammen...

```
PERL WARNING: Use of uninitialized value in sprintf at (eval 762) line 1.
2018.03.03 12:19:04 1 : PERL WARNING: Missing argument in sprintf at (eval 762) line 1.
2018.03.03 12:19:04 1 : PERL WARNING: Use of uninitialized value in sprintf at (eval 763) line 1.
2018.03.03 12:19:04 1 : PERL WARNING: Missing argument in sprintf at (eval 763) line 1.
```

**Comment by SamNitro** [comment]
Bei mir auch, gibt es schon was neues??

**Comment by Cooper81** [comment]
habs leider auch. und mittlerweile kein fhem logo oben links mehr :(

**Comment by klein0r** [comment]
Ja, das ist leider nicht anders machbar. Das wird so lange angezeigt, bis das JavaScript geladen wurde und die Meldung ausblendet. Daher kommt es ab und zu eben zu kleinen Verzögerungen.
