### ISSUE TITLE
Connection lost, trying a reconnect every 5 seconds.

### ISSUE THREAD

**Issue by Dergemer** [klein0r/fhem-style-haus-automatisierung#52]
nach Update auf Version 2.6 (über update all) kommt das immer wieder.
Habe bis jetzt nur Dinge aus deinen Videos implementiert...

**Comment by ChrisXYZ1** [comment]
Hallo, habe das selbe Problem nach dem ic das Proxy Lets encrypt https gemacht habe ... Nurnoch diese meldung

**Comment by Dergemer** [comment]
ja, geht bei mir auch. danke für's erinnern, dass das geschlossen werden kann!
