### ISSUE TITLE
Modul PostMe Set/Get Elemente -> Fehlender Hintergrund

### ISSUE THREAD

**Issue by Quantum1337** [klein0r/fhem-style-haus-automatisierung#53]
Hallo,
vielen Dank für den super FHEM-Style! Mir ist ein kleiner Fehler im Modul PostMe aufgefallen. Die Set/Get Elemente haben keinen Hintergrund. Siehe Screenshot:

![grafik](https://user-images.githubusercontent.com/36477626/37259384-cd7ce4d2-2585-11e8-816e-96c670c6ff1f.png)

Grüße

**Comment by klein0r** [comment]
Das Modul bietet mir leider nach wie vor extrem wenig CSS-Klassen an, sodass ich dafür das Design nicht anpassen kann
