### ISSUE TITLE
Links für DELETEATTR gehen verlogneren wenn attribute sehr lang

### ISSUE THREAD

**Issue by JoschaMiddendorf** [klein0r/fhem-style-haus-automatisierung#60]
![bildschirmfoto 2018-04-21 um 00 30 48](https://user-images.githubusercontent.com/19818109/39076434-8c5499c4-44fb-11e8-8647-514878203f72.png)

**Comment by klein0r** [comment]
Sollte in den aktuellen Versionen bereits behoben sein

**Comment by JoschaMiddendorf** [comment]
Ich mir in letzter Zeit auch nicht mehr aufgefallen.
