### ISSUE TITLE
HSVp inline wird nicht korrekt angezeigt

### ISSUE THREAD

**Issue by s1738berger** [klein0r/fhem-style-haus-automatisierung#61]
Wenn für ein Licht als Farbwähler HSVp ausgewählt ist, so wird das PopUp nicht korrekt angezeigt.
Die beiden Bilder ziegen was erwartet ist und was mit dem Stylesheet von  hausautomatisierung_com (v2.6 aktuell) angezeigt wird. Anscheinend fehlen ein paar Klassen im CSS.
Vielen Dank für's gelegentliche Korrigieren. 
Gruss Stefan

![hsvp-fhem](https://user-images.githubusercontent.com/368973/40716385-217b804a-6409-11e8-9298-47f1f39789c3.png)
![hsvp-ha](https://user-images.githubusercontent.com/368973/40716386-219bcfda-6409-11e8-9001-0d63d8d0e387.png)

**Comment by klein0r** [comment]
Ist in 2.10 dann auch endlich behoben (wird bald freigegeben)
