### ISSUE TITLE
Deaktivierte Eingabezeile hat Anzeigefehler

### ISSUE THREAD

**Issue by jpawlowski** [klein0r/fhem-style-haus-automatisierung#62]
Hallo Matthias,

herzlichen Dank für die aktualisierte Version heute! Kommt zur richtigen Zeit :-)

Mit ist aufgefallen, dass es einen Anzeigefehler gibt, wenn man mittels

`attr WEB hiddenroom input`

die Eingabezeile ausblendet (beispielsweise weil man unterschiedliche Frontends für Benutzer und Admins hat und die Eingabezeile im Benutzer-Frontend gerne ausblendet). Siehe Screenshot:

![image](https://user-images.githubusercontent.com/75446/41981212-a6f81366-7a28-11e8-96d3-75ccd8a98907.png)

Ich bin nicht sicher, ob man das im CSS fixen kann oder ob der FHEM Code dafür besser gepatcht werden sollte, damit das HTML Objekt ganz verschwindet.

Viele Grüße
Julian

**Comment by Lazgar** [comment]
Leider wird der Platz, welcher durch die Eingabezeile belegt wird, auch nach dem ausbleden nicht freigegeben, egal welches Theme man verwendet... Vielleicht kann ja Matthias etwas entsprechendes bauen, wenn man es schon ausblendet, die Devices dann auch entsprechend nach oben gerückt werden.

**Comment by klein0r** [comment]
Verrückt was alles geht 👍 Habe die Leiste ehrlich gesagt noch nie ausgeblendet. Wieder etwas gelernt. Muss ich mir im Detail anschauen

**Comment by klein0r** [comment]
Wird in 2.8 behoben sein
