### ISSUE TITLE
Version 2.7 - Anzeigefehler

### ISSUE THREAD

**Issue by Lazgar** [klein0r/fhem-style-haus-automatisierung#63]
Bei Änderungen die sich auf die Config auswirken, wird die orange Umrandung bei dem Icon von Save config nicht richtig platziert, die beiden orangen Balken sind leicht nach unten verschoben...nur Kosmetik

![save config](https://user-images.githubusercontent.com/34341913/42024657-fcade228-7ac2-11e8-82c0-1154c4bc8d88.jpg)

Wenn man versucht, sich die letzten Änderungen anzusehen, bekommt man kein Popup so wie früher, es wird einem zwar angezeigt, jedoch unterhalb des Navigationsbereichs + entsprechender Fehlermeldung -> siehe Screenshot

![last changes](https://user-images.githubusercontent.com/34341913/42024683-07a71dd4-7ac3-11e8-9ba1-e5a8d2c9d28e.jpg)

**Comment by Lazgar** [comment]
Also letzteres ist wohl eher mein verschulden. Da haben sich scheinbar einige Java scripte nicht vertragen die ich im entsprechenden FHEMWEB eingebunden hatte, alles gut!

**Comment by klein0r** [comment]
Danke, das Icon schaue ich mir an 👍

**Comment by kabiz** [comment]
Hi, ich habe den selben Anzeigefehler bei Save config. 
Gibt es dies bzgl. schon eine Lösung?

Mit freundlichen Grüßen und vielen Dank für deine ganzen Mühen
kabiz

**Comment by klein0r** [comment]
Wird in 2.8 behoben sein
