### ISSUE TITLE
"Scroll to top" in lokaler Commandref funktioniert nicht

### ISSUE THREAD

**Issue by jpawlowski** [klein0r/fhem-style-haus-automatisierung#64]
In der modularen Commandref (wir aktiviert über "attr global commandref modular") bleibt der Link "Scroll to top" nicht an seiner Stelle, sondern wird beim Scrollen mit dem Text zusammen aus dem Sichtfeld gescrollt und kann somit nicht benutzt werden.
![image](https://user-images.githubusercontent.com/75446/42139096-7cd1dce0-7d87-11e8-9dbe-85fa02ac8a70.png)

**Comment by klein0r** [comment]
Das kann ich leider nicht anpassen, da ich nicht unterscheiden kann, ob ich in der Commandref bin oder im "normalen" WEB. FHEM sei dank...

**Comment by jpawlowski** [comment]
Crosslink: https://forum.fhem.de/index.php/topic,91204.0.html

**Comment by klein0r** [comment]
@jpawlowski Das ist ein netter Versuch 😄 Im Forum bin ich nicht gerne gesehen (alles wird als Werbung gewertet) und CoolTux hat mich darum gebeten, dass wir beim "Sie" bleiben. Daher habe ich alle Beiträge von mir im Forum gelöscht. Und dann fragt man sich, warum ich das dort nicht platziere?! Naja.

Eine Anfrage nach mehr Klassen und IDs gibt es bereits seit 2013 vergebens.
https://forum.fhem.de/index.php/topic,14081.msg88451.html#msg88451

**Comment by jpawlowski** [comment]
Ich kenne eure Diskussionspunkte nicht, ich habe CoolTux bisher als eher einen aus der pragmatischeren Fraktion erlebt... aber ja, die Community und Entwicklergemeinde ist schwierig (kann man auch bei mir nachlesen ;-)).

Anyway, die Entwickler Wunschliste ist glaube ich eher ein Datengrab, da schaut nie jemand rein und es gerät leider schnell in Vergessenheit.

Es gab auch tatsächlich 2 konstruktive Rückmeldungen für dieses spezielle Problem:

```
1. Vorschlag
body[style="word-wrap: break-word;"]>#menuScrollArea>#menu {position: fixed;}

2. Vorschlag
a[href=#doctop]
```

Vielleicht hilft es ja doch noch.

**Comment by klein0r** [comment]
Ich kenne die eigentlich auch nicht 😄 

Die beiden Vorschläge sind ziemlich ... unschön. Funktioniert zwar heute, aber wer weiß wie es beim nächsten Update ist? Warum vergibt man nicht einfach eine neue Klasse an den Elementen? Sich auf Inhalte von anderen Attributen im HTML zu beziehen, um dann neue Styles da drauf zu packen ist wirklich gefrickelt (besonders der erste).

**Comment by jpawlowski** [comment]
Stimme ich dir absolut zu. Leider muss man wirklich um jedes Wort im Code eine Grundsatzdiskussion anfangen... Die Klassen zu vergeben scheint Rudi zu viel (Maintenance)Aufwand zu sein, daher verschiebt er den Aufwand gerne zu anderen, damit die dann konstant den Änderungen hinterher laufen. Bin auch seit 2 Jahren kaum noch an der Entwicklung beteiligt und mache wirklich nur noch, was mir selbst hilft.
Zwischen den Zeilen will er mit seinem neuen f18 Theme ja zeigen, dass man absolut alles anpassen kann, aber dass das Theme mal wieder viel zu technisch geworden ist, sieht man ja.

Lange Rede, kurzer Sinn: Erfahrungsgemäß ändert sich selten etwas so dramatisches, dass du befürchten musst dauernd das CSS nachzuziehen. Das ist das einzig Gute an Rudis Blockadehaltung was Veränderung angeht. Wenn da was in diesem Theme hier bricht, dann bricht es halt und entweder fällt es jemandem auf und er meldet es hier, oder es ist dann eben kaputt. Kann man dann ja hier nachlesen warum das so ist :-)
