### ISSUE TITLE
Eingabezeile

### ISSUE THREAD

**Issue by ChristhardM** [klein0r/fhem-style-haus-automatisierung#65]
Der Rahmen der Eingabezeile taucht wieder auf, wenn man die Seite ganz nach unten gescrollt hat. Wenn man nach unten scrollt, ist er zwischenzeitlich verschwunden. Ist man unten angekommen, taucht der Rahmen wieder auf und bleibt, wenn man wieder nach oben scrollt.

**Comment by klein0r** [comment]
Richtig, das ist Absicht. Machen ganz viele Seiten so 👍
