### ISSUE TITLE
Version 2.7 - Notifys aus Eventmonitor erzeugen funktioniert nicht mehr

### ISSUE THREAD

**Issue by reibuehl** [klein0r/fhem-style-haus-automatisierung#66]
Wenn ich im Eventmonitor eine Zeile markiere und dann mit dem Button "Create/Modify" versuche, ein Notify anzulegen, bekomme ich ein Popup mit der Fehlermeldung

> console.js line 304:
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

anstatt des Popups zur Definition des Notifys. Mit dem default Style klappt es. 

Ich benutze die Version 2.7 des Styles.
![capture](https://user-images.githubusercontent.com/4268514/42697438-652015a2-86bb-11e8-9447-d3e5f9c40992.jpg)

**Comment by klein0r** [comment]
Klappt bei mir. Mit der console.js habe ich auch nichts zu tun 😄 
Bitte Update von FHEM machen und erneut versuchen
