### ISSUE TITLE
Falsche Schrift mit SVG Plots

### ISSUE THREAD

**Issue by s1738berger** [klein0r/fhem-style-haus-automatisierung#67]
Seit diesem Update ( # $Id: 98_SVG.pm 16985 2018-07-15 14:08:15Z rudolfkoenig $ ) des SVG Moduls wird auf Seiten auf denen min. ein Plot dargestellt wird ist, wird die Schrift der ganzen Seitre, nicht nur des Plots, mit Serifen dargestellt. ( scheint Times anstelle von Verdana zu sein )
Eigentich deutet das auf ein Problem in dem Modul hin, dieses Verhalten tritt nur mit dem Style hausautomatisierung auf.... Wahrscheinlich ist die Ursache im SVG Modul, muss jedoch im Skin angepsst werden..
Mit der manuellen Rückinstallation von ( # $Id: 98_SVG.pm 16830 2018-06-07 10:18:21Z rudolfkoenig $ ) funktioniert alles wieder wie gewünscht.
Dank für's gelegentliche Ansehen..
Gruss, Stefan

**Comment by AlxMag** [comment]
das musst du in der hausautomatisierung_comsvg_style.css ändern:
aus html, body, div, span, applet, object, .... (3. Zeile)
font und font-size entfernen, dann passt's wieder (jedenfalls bei mir)

**Comment by s1738berger** [comment]
Funktionert perfekt, danke für den Tip, AlxMag.
Dann wird diese Anpassung bestimmt im nächsten Update des Skins integriert sein.

**Comment by smoki3** [comment]
https://github.com/klein0r/fhem-style-haus-automatisierung/pull/71

Das sollte es dann beheben!
