### ISSUE TITLE
Schriftart ändert sich beim durchklicken im Menue

### ISSUE THREAD

**Issue by HessyJames** [klein0r/fhem-style-haus-automatisierung#69]
Hallo Zusammen,

ich habe folgendes Problem: seit dem Uptade auf 2.7 ändert sich die Schriftart in der gesamten FHEM Umgebung wenn ich manche Räume anklicke...

Grüße
Hessy James

**Comment by s1738berger** [comment]
Ev. das gleiche Problem wie issue https://github.com/klein0r/fhem-style-haus-automatisierung/issues/67 ?

**Comment by HessyJames** [comment]
Hi,

genau das wars! 

Vielen Dank!
Grüße
Hessy James

**Comment by smoki3** [comment]
https://github.com/klein0r/fhem-style-haus-automatisierung/pull/71

Das sollte es dann beheben!

**Comment by klein0r** [comment]
Wird in 2.8 behoben sein
