### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by plin2** [klein0r/fhem-style-haus-automatisierung#75]
Ich habe drei FHEM-Instanzen laufen und würde gerne die Beschrifung oben links sowie das Hintergrundbild individuell gestalten. Gibt es dafür einen "schönen" Weg via Parametrierung über FHEM oder nur harte Eingriffe in Code und/oder CSS?

**Comment by klein0r** [comment]
Harte Eingriffe sind nicht nötig. Du kannst deine eigene CSS-Datei ablegen und dann einbinden. Einfach die Optionen dann überschreiben. Dann bleibt das Ganze auch Update-Sicher
