### ISSUE TITLE
JS wird nicht geladen

### ISSUE THREAD

**Issue by ArrestedOps** [klein0r/fhem-style-haus-automatisierung#76]
Obwohl ich die JS EInstellungen im Web vorgenommen habe, bekomme ich in Fhem eine Fehlermeldung, wenn ich z.b. die Icons öffne:
![image](https://user-images.githubusercontent.com/43731327/46263114-4eabe380-c50b-11e8-9beb-097476a7694a.png)

Dazu noch ein Screenshot vom Web:
![image](https://user-images.githubusercontent.com/43731327/46263142-831f9f80-c50b-11e8-804f-941e91eb1aca.png)

**Comment by klein0r** [comment]
Welchen Browser nutzt Du?

**Comment by socram84** [comment]
Das liegt aller Wahrscheinlichkeit nach daran, dass du das vorherige Theme nicht sauber deinstalliert hast, schätze ich.
Mit sudo rm -rf /opt/fhem/www/hausautomatisierung-com/ den Ordner löschen, dann update check ha_theme und update all ha_theme.

Nun noch bei select style den theme auswählen.
