### ISSUE TITLE
Eigenes Hintergrundbild

### ISSUE THREAD

**Issue by wolwin** [klein0r/fhem-style-haus-automatisierung#79]
Ändert man das Hintergrundbild 'bg_wrapper.jpg' (habe es mit IrfanView dunkler gemacht, da die weiße LOG-Schrift nicht sichtbar ist), dann wird es bei einem FHEM Update immer wieder zurückgesetzt. Setzt man den 'root' User für 'bg_wrapper.jpg', kommt der gesamte Updatevorgang zum Stillstand. 
Es wäre schön, wenn das geändert werden könnte (config.ini mit Eintrag auf eigenes Bild???)!

**Comment by rudibarani** [comment]
Hallo Wolwin,
einfach folgenden Eintrag bei FHEM machen: 
attr global exclude_from_update www/hausautomatisierung-com/images/bg_wrapper.jpg

**Comment by wolwin** [comment]
Hallo, 
Danke für die Info - habe die Zeile eingetragen und ein Github Update hat das eigene Hintergrundbild nicht überschrieben!
