### ISSUE TITLE
Plot-/SVG-Farben können nicht eingestellt werden

### ISSUE THREAD

**Issue by klein0r** [klein0r/fhem-style-haus-automatisierung#8]

**Comment by reibuehl** [comment]
Ich bin (vermutlich) auf das gleiche Problem gestoßen: Im SVG Plot Editor ist das Dropdown Feld für die Linienart nicht vorausgefüllt und lässt sich auch nicht manuell beschreiben. Das Feld heißt "style_0" im HTML Form "pedit". Hier sollten eigentlich die folgenden Werte auswählbar sein:

l0
l1
l2
l3
l4
l5
l6
l7
l8
l0fill
l1fill
l2fill
l3fill
l4fill
l5fill
l6fill
l7fill
l8fill
