### ISSUE TITLE
config.file nur auf der Hauptseite zu speichern (via Icon)

### ISSUE THREAD

**Issue by mparal** [klein0r/fhem-style-haus-automatisierung#80]
Ein speichern auf einer der unterkategorisierten Seiten meldet nach drücken des Icons ein erfolgreiches speichern jedoch erfolgt KEINE Abspeicherung. Das Icon selbst behält seine beiden senkrechten roten Balken. Nach Rückkehr auf die Hauptseite kaqnn abgespeichert werden.

**Comment by klein0r** [comment]
Was meinst Du mit "unterkategorisierten Seiten"? Bei mir funktioniert es überall
