### ISSUE TITLE
Seite meldet Java Skript fehlt

### ISSUE THREAD

**Issue by marv160** [klein0r/fhem-style-haus-automatisierung#81]
Hi, 
leider ist im Them wohl ein kleiner Bugg. Wenn man im FireFox die Log Datei einsehen will bleibt die Seite hängen. Unter der Eingabezeile erscheint "Them-JS aktivieren für vollen Funktionsumfang attr WEB..." ich habe aber aus der Anleitung genau diesen Teil als Attribut im WEB eingegeben. Danach meldet FireFox, der Tab ist abgestürzt. FHEM, Raspberry sind auf neustem Stand. Es sind keine weiteren Installationen auf dem Raspberry. Am FHEM hängt nur ein SignalDuino.

**Comment by klein0r** [comment]
Kann ich nicht reproduzieren
