### ISSUE TITLE
editConfig = 0 funktioniert nicht

### ISSUE THREAD

**Issue by tomtiger65** [klein0r/fhem-style-haus-automatisierung#82]
Seit dem ich das Style "hausautomatisierung_com" installiert/aktiviert habe, hat eine Änderung des Attributes "editConfig=0" im WEB Device keinen Effekt mehr - man kann die Datei "fhem.cfg" editieren.

Auch im im Style "Default" zieht nun dieser Schalter nicht mehr.

Was mir aufgefallen ist: das Editierfenster für die Datei "fhem.cfg" zunächst weiß (default) hinterlegt un schaltet dann um auf Hintergrund schwarz - ist bei beiden Style's so (andere habe ich nicht ausprobiert).

**Comment by klein0r** [comment]
Da kann das Theme nichts für. Scheint ein Bug in aktuellen FHEM-Versionen zu sein, dass editConfig = 0 keine Funktion mehr hat
