### ISSUE TITLE
Floorplan: Icons/Elemente werden nicht an der richtigen Stelle angezeigt

### ISSUE THREAD

**Issue by reibuehl** [klein0r/fhem-style-haus-automatisierung#87]
Wenn ich den Floorplan auswähle, werden die Icons und Bedienelemente nach links verschoben und nicht an der Stelle angezeigt, an der sie beim Default Skin erscheinen.

Im Anhang zwei Screenshots die den gleichen Floorplan zeigen, einmal mit Default Skin, einmal mit der Hausautomatisirerung.com Skin.

![default](https://user-images.githubusercontent.com/4268514/52280016-26217380-295b-11e9-8488-e02b88cfcc46.png)
![hausautomatisierung com-png](https://user-images.githubusercontent.com/4268514/52280019-26ba0a00-295b-11e9-9e38-88d5634cf407.PNG)

**Comment by reibuehl** [comment]
Was mir noch aufgefallen ist: Normalerweise komme ich mit einem klick auf das Hausautomatisierungs-Logo links oben immer nach /fhem? zurück. Wenn ein Floorplan angezeigt wird, scheint der Link zu fehlen und es gibt keinen Weg raus aus dem Floorplan außer man benützt den Back Button des Browsers.

**Comment by klein0r** [comment]
Im Floorplan werden die Positionen immer relativ gespeichert. Das heißt, dass Du nach ändern des Styles (dank anderer Breite) die Icons noch einmal verschieben musst.
