### ISSUE TITLE
Missing CSS classes "even" and "odd"

### ISSUE THREAD

**Issue by jpawlowski** [klein0r/fhem-style-haus-automatisierung#90]
Hi Matthias,

it seems that CSS classes "even" and "odd" are not included or not considered for HTML tables that are used within popup windows in FHEMWEB:

![image](https://user-images.githubusercontent.com/75446/53873970-b823a700-4001-11e9-9290-540b6e930c28.png)

As you can see from this screenshot, the table is not showing any background colors for the different lines of the table.

It looks very much different in the FHEM standard theme however:
![image](https://user-images.githubusercontent.com/75446/53874084-02a52380-4002-11e9-8767-24bf0b46b293.png)

You may also notice that the headline looks different between the two styles as the inline <b></b> blocks do not seem to be considered as well.

Can you fix that? :-)

**Comment by jpawlowski** [comment]
FHEMWEB got a fix in terms of HTML handling. However, it seems it would still be beneficial to allow proper rendering of the popup content.

Some updated screenshots:
<img width="341" alt="image" src="https://user-images.githubusercontent.com/75446/54416528-f014a380-46ff-11e9-8558-10847f0c62a8.png">
<img width="807" alt="image" src="https://user-images.githubusercontent.com/75446/54416552-0458a080-4700-11e9-9534-598db146eff8.png">

**Comment by jpawlowski** [comment]
Additional note:
The same output may also appear directly on FHEM pages where table content is already handled correctly. However, <h*> tags are still ignored:
![image](https://user-images.githubusercontent.com/75446/54521597-87316380-496b-11e9-94c8-d12665490498.png)
(this example was produced by FHEM Installer / 98_Installer.pm)

**Comment by klein0r** [comment]
👍
