### ISSUE TITLE
JavascriptEditor (Codemirror)

### ISSUE THREAD

**Issue by SteRa2020** [klein0r/fhem-style-haus-automatisierung#91]
Seit dem letzten Update verstellt sich die Breite vom DEF-Editor mit Code-Mirror nicht mehr.
Bei zu langem Text wird ein Zeilenumbruch erzwungen ohne Zeilennummer und der Cursor wird zwei Zeilen groß. 
Bei einem anderen Style ist es nicht so. 
Ist das Problem bekannt?

**Comment by Dave2526** [comment]
Hab das gleiche Problem festgestellt

**Comment by casimir612** [comment]
Habe leider das selbige Phenomen festellen müssen.

**Comment by ghost** [comment]
Habe auch das Problem festgestellt, Matthias. :-(

**Comment by klein0r** [comment]
Echt komisch. Das Problem lässt sich aktuell lösen, wenn auf dem Web-Device das Attribut codemirrorParam setzt und lineWrapping auf true setzt:

`attr WEB codemirrorParam { "theme": "blackboard", "lineNumbers":true, "lineWrapping": true, "height": "auto" }`

Ich zwinge den Editor aktuell zum Zeilenumbruch - und damit kommt er nicht klar. Das ändere ich.
