### ISSUE TITLE
< br >  Wird im Stateformat nicht beachtet

### ISSUE THREAD

**Issue by flummy1978** [klein0r/fhem-style-haus-automatisierung#92]
Beim nachbauen eines Tipps (https://haus-automatisierung.com/hardware/fhem/2017/11/16/fhem-quicktipps-2.html)  nämlich das Stateformat mit Hilfe des < BR > Tags zu unterteilen ist, mir aufgefallen, dass der Tag hier nicht beachtet wird. Screenshot jeweils mit Standard CSS und der haus-automatisierung :) 

Grüße
Andreas
![screen3](https://user-images.githubusercontent.com/49339206/55686837-79696f80-5966-11e9-990c-e253044b071d.jpg)

Edit: Nachdem ich jetzt noch ein wenig gebastelt hab, bin ich wieder auf die gleiche Seite gekommen und siehe da.... auf Einmal wurde der < br > Tag genauso interpretiert wie im Originalen Style :)

**Comment by klein0r** [comment]
Wird in 2.10 wieder klappen 👍
