### ISSUE TITLE
Das kleine + icon

### ISSUE THREAD

**Issue by ghost** [klein0r/fhem-style-haus-automatisierung#94]
Das kleine + wird links ausgerichtet beim öffnen z.b. Devices. Dies macht Texte unsichtbar

**Comment by jpawlowski** [comment]
Überhaupt nicht klar, was hier überhaupt der Fehler sein soll... die Beschreibung ist weder verständlich noch nachvollziehbar.

**Comment by ghost** [comment]
Julian Du hast völlig Recht. Meinen Fehler. Danke für dein Bericht

**Comment by klein0r** [comment]
Verstehe ich auch nicht. Da scheinbar keine weitere Beschreibung erfolgt, mache ich zu
