### ISSUE TITLE
+ icon hat keine function

### ISSUE THREAD

**Issue by ghost** [klein0r/fhem-style-haus-automatisierung#95]
Das + icon an die oberseite hat keine Function.
Wenn mann ein command eingibt dann erscheint ein neues window. (klick auf +) Mann "denkt" das mann das command erneut eingeben muss. Wenn mann nacher auf das + klickt dan sieht mann die Fehler Meldung: Executing the update the background.
Also das + macht keinen Sinn.

ENTER eingeben sorgt dafür das das command ausgeführt wird.

Vielen Dank.

**Comment by jpawlowski** [comment]
Die Funktion interpretierst du falsch.
Das "plus" ist nicht zur Bestätigung des Befehls aus der Befehlszeile gedacht, sondern um mehrere Befehle hintereinander komfortabel per copy&paste auszuführen, nachdem man sie in das popup fenster reinkopiert hat.

Die Funktion ist neu in FHEMWEB und hat nichts mit dem FHEM Style hier zu tun

Mehr Infos:
https://forum.fhem.de/index.php/topic,96921.msg927192.html#msg927192

**Comment by ghost** [comment]
Julian vielen Dank für deine Antwort. Du hast völlig recht! Meinem Fehler.
Gruss aus Holland.

Ron
