### ISSUE TITLE
DEF-Editor ist zu breit und der Zeilenumbruch erfolgt nicht

### ISSUE THREAD

**Issue by GammaTwin** [klein0r/fhem-style-haus-automatisierung#96]
Der rechte Bereich von FHEM ist bei mir 1000 Pixel breit. Öffne ich den DEF-Editor, wird dieser 1380 Pixel breit.
Der Zeilenumbruch erfolgt auch nicht mehr im DEF-Editor.

`attr WEB JavaScripts codemirror/fhem_codemirror.js`
`attr WEB codemirrorParam { "theme": "blackboard", "lineNumbers":true, "lineWrapping": true, "height": "auto" }`
`attr WEB roomIcons Save.config:message_attention`
`attr WEB stylesheetPrefix hausautomatisierung_com`

**Comment by ghost** [comment]
@GammaTwin Da hast Du recht. Habe Ich auch.

**Comment by klein0r** [comment]
In Version 2.10? Da habe ich das eigentlich behoben (dachte ich)

**Comment by GammaTwin** [comment]
> 
> 
> In Version 2.10? Da habe ich das eigentlich behoben (dachte ich)

ja, in 2.10

Im Beittrag #97 ist ein Screenshot davon
