### ISSUE TITLE
DEF Editor zu breit!!!!

### ISSUE THREAD

**Issue by ghost** [klein0r/fhem-style-haus-automatisierung#97]
![ha-screenshot](https://user-images.githubusercontent.com/4492243/56572430-56be9400-65bf-11e9-9e19-9117bd4e9ff4.jpg)

Matthias.
Es ist schon eine weile her aber wann wird deine HA template repariert?

Der DEF Editor ist  viel, viel zu breit.
Wen Du der DEF Editor klickst dann siehst Du das bestimmte Zeilen unendlich nach Rechts ausrichten.
Auf diese weise sieht es nicht so ganz "Hi Tech" aus ;-)
So wie Du siehst ist die Version 2.10 installiert.

Vielen Dank für deine mühe.

Gruss aus Holland.

Ron Willems

**Comment by klein0r** [comment]
Sollte in 2.11 gelöst sein
