### ISSUE TITLE
Nach Update Version 2.8 und 2.10 in der Anzeige

### ISSUE THREAD

**Issue by marios774** [klein0r/fhem-style-haus-automatisierung#98]
Es werden mir nach einem Update nun beide Versionsnummern angezeigt, der Hilfebutton ist ebenfalls für beide Versionen.

**Comment by The-Deep-Sea** [comment]
Einmal den Browser-Cache leeren (Strg + F5) sollte das Problem lösen. Zumindest war dies bei mir der Fall.

**Comment by marios774** [comment]
Das nützt nix, auch auf anderen Rechnern und mit neuen Browsern, überall das gleiche . Beide Versionsnummern und beide Theme-Fehler Zeilen 2.8  und 2.10.

**Comment by klein0r** [comment]
Unter WEB die JavaScript-Datei rausnehmen. Das wurde umgebaut und ich kann jetzt eine eigene Style-Datei mitgeben.

`attr WEB JavaScripts codemirror/fhem_codemirror.js`
