### ISSUE TITLE
Fehlerhafte Darstellung der Gruppen

### ISSUE THREAD

**Issue by gary822** [klein0r/fhem-style-haus-automatisierung#99]
Ich habe gerade festgestellt das die Gruppendarstellung der einzelnen Räume fehlerhaft ist.

In manchen Räumen werden die Gruppen über die gesamte Breite angezeigt und bei manchen nur auf die Länge der Devices:
![grafik](https://user-images.githubusercontent.com/48492786/57856994-7b88de80-77ee-11e9-9acb-9ce9be214caa.png)
![grafik](https://user-images.githubusercontent.com/48492786/57857032-952a2600-77ee-11e9-9dd0-987d71e0d042.png)

**Comment by s1738berger** [comment]
das Problm scheint nur bei readgsGroups zu sein ( Version 2.11 )

**Comment by gary822** [comment]
die (in meinem Fall) angesprochenen Systemgeräte sind eine normale Gruppe.
Aber ja bei readingsGRoup ist es ebenfalls der Fall sofern diese alleine stehen.

**Comment by Roadrunner1106** [comment]
Ich bin mir sicher sicher, ob die Ursache meines Problems die gleiche ist. 

Ich hatte eine group erstellt und verschiedene Objekte für mein Smart Meter hinzugefügt. Das Objekt SVG kann ich jetzt nicht mehr in der Gruppe auswählen (Link fehlt), um es bearbeiten zu können. Hier mal ein Screenshot (SVG ist rot umrahmt).

<img width="961" alt="Bildschirmfoto 2019-05-27 um 20 21 44" src="https://user-images.githubusercontent.com/51094320/58434805-c8f22f00-80bd-11e9-8a79-cf141a42f2c2.png">

**Comment by s1738berger** [comment]
Inn der Datei hausautomatisierung_comstyle.css ( 2.14 ) habe ich auf Zeile 95
#content > table { width: 100%; }

ersetzt mit:
#content table { width: 100%; }

damit scheint sieht es für mich gut aus. Die ReadingsGroups haben nun die ganze Breite.

**Comment by klein0r** [comment]
@s1738berger Damit machst du jede Tabelle innerhalb des Content-Bereichs 100% breit. Das wird an dieser Stelle eventuell klappen, aber an vielen anderen Stellen das Design kaputt machen.

**Comment by s1738berger** [comment]
Ja, das gilt für jede Tabelle im Content. Sieht für mich gut aus, speziell für ReadingGroups. Ev. Nutze ich nicht alle Möglichkeiten, wo es wirksam werden kann.
Gruss Stefan

**Comment by aHVzY2g** [comment]
@Roadrunner1106 bei mir tritt der selbe fehler auf
